// This file is auto-generated. DO NOT EDIT BY HAND
// Use generate_data.py to rebuild this file if needed

// https://doc.qt.io/qt-5/qtqml-javascript-resources.html
.pragma library

var currencies = {
	"ADA": {"code": "ADA", "name": "Cardano", },
	"ATOM": {"code": "ATOM", "name": "Cosmos", },
	"BCH": {"code": "BCH", "name": "Bitcoin Cash", "symbol": "฿", },
	"BNB": {"code": "BNB", "name": "Binance Coin", },
	"BSV": {"code": "BSV", "name": "Bitcoin SV", },
	"BTC": {"code": "BTC", "name": "Bitcoin", "symbol": "₿", },
	"BTG": {"code": "BTG", "name": "Bitcoin Gold", },
	"BUSD": {"code": "BUSD", "name": "Binance USD", "symbol": "B$", },
	"COMP": {"code": "COMP", "name": "Compound", },
	"CZK": {"code": "CZK", "name": "Czech Krown", "symbol": "Kč", },
	"DASH": {"code": "DASH", "name": "Dash", },
	"DOGE": {"code": "DOGE", "name": "Dogecoin", },
	"DOT": {"code": "DOT", "name": "Polkadot", },
	"ETC": {"code": "ETC", "name": "Ethereum Classic", },
	"ETH": {"code": "ETH", "name": "Ethereum", "symbol": "Ξ", },
	"EUR": {"code": "EUR", "name": "Euro", "symbol": "€", },
	"FIL": {"code": "FIL", "name": "Filecoin", },
	"GAME": {"code": "GAME", "name": "GameCredits", },
	"GBP": {"code": "GBP", "name": "British Pound", "symbol": "£", },
	"JPY": {"code": "JPY", "name": "Japanese Yen", "symbol": "¥", },
	"LINK": {"code": "LINK", "name": "Chainlink", },
	"LSK": {"code": "LSK", "name": "Lisk", },
	"LTC": {"code": "LTC", "name": "Litecoin", "symbol": "Ł", },
	"LUNA": {"code": "LUNA", "name": "Terra", },
	"MKR": {"code": "MKR", "name": "Maker", },
	"PLN": {"code": "PLN", "name": "Polish Zloty", "symbol": "zł", },
	"UNI": {"code": "UNI", "name": "Uniswap", },
	"USD": {"code": "USD", "name": "US Dollar", "symbol": "$", },
	"USDC": {"code": "USDC", "name": "USD Coin", "symbol": "$C", },
	"USDT": {"code": "USDT", "name": "USD Tether", "symbol": "$T", },
	"XLM": {"code": "XLM", "name": "Stellar", },
	"XMR": {"code": "XMR", "name": "Monero", },
	"XRP": {"code": "XRP", "name": "Ripple", "symbol": "Ʀ", },
	"ZEC": {"code": "ZEC", "name": "ZCash", },
}
var exchanges = {
	"binance-com": {
		"name": "Binance",
		"url": "https://binance.com/",
		"api_url": "https://api1.binance.com/api/v3/trades?limit=1&symbol={crypto}{pair}",
		"getRateFromExchangeData": function(data, crypto, pair) {
			return data[0].price
		},
		"pairs": {
			"ADA": ["BNB","BTC","BUSD","ETH","EUR","GBP","USDC","USDT",],
			"ATOM": ["BNB","BTC","BUSD","USDC","USDT",],
			"BCH": ["BNB","BTC","BUSD","EUR","USDC","USDT",],
			"BNB": ["BTC","BUSD","ETH","EUR","GBP","USDC","USDT",],
			"BTC": ["BUSD","EUR","GBP","USDC","USDT",],
			"BTG": ["BTC","BUSD","ETH","USDT",],
			"BUSD": ["USDT",],
			"COMP": ["BNB","BTC","BUSD","USDT",],
			"DASH": ["BNB","BTC","BUSD","ETH","USDT",],
			"DOGE": ["BNB","BTC","BUSD","EUR","GBP","USDC","USDT",],
			"DOT": ["BNB","BTC","BUSD","EUR","GBP","USDT",],
			"ETC": ["BNB","BTC","BUSD","ETH","EUR","USDC","USDT",],
			"ETH": ["BTC","BUSD","EUR","GBP","USDC","USDT",],
			"EUR": ["BUSD","USDT",],
			"FIL": ["BNB","BTC","BUSD","USDT",],
			"GBP": ["BUSD","USDT",],
			"LINK": ["BTC","BUSD","ETH","EUR","GBP","USDC","USDT",],
			"LSK": ["BNB","BTC","ETH","USDT",],
			"LTC": ["BNB","BTC","BUSD","ETH","EUR","GBP","USDC","USDT",],
			"LUNA": ["BNB","BTC","BUSD","EUR","USDT",],
			"MKR": ["BNB","BTC","BUSD","USDT",],
			"UNI": ["BNB","BTC","BUSD","EUR","USDT",],
			"USDC": ["BNB","BUSD","USDT",],
			"XLM": ["BNB","BTC","BUSD","ETH","EUR","USDC","USDT",],
			"XMR": ["BNB","BTC","BUSD","ETH","USDT",],
			"XRP": ["BNB","BTC","BUSD","ETH","EUR","GBP","USDC","USDT",],
			"ZEC": ["BNB","BTC","BUSD","ETH","USDC","USDT",],
		},
	},
	"bitstamp-net": {
		"name": "Bitstamp",
		"url": "https://bitstamp.net/",
		"api_url": "https://www.bitstamp.net/api/v2/ticker/{crypto}{pair}",
		"getRateFromExchangeData": function(data, crypto, pair) {
			return data.ask
		},
		"pairs": {
			"BCH": ["BTC","EUR","GBP","USD",],
			"BTC": ["EUR","GBP","USD","USDC",],
			"ETH": ["BTC","EUR","GBP","USD","USDC",],
			"EUR": ["USD",],
			"GBP": ["EUR","USD",],
			"LINK": ["BTC","ETH","EUR","GBP","USD",],
			"LTC": ["BTC","EUR","GBP","USD",],
			"MKR": ["BTC","EUR","USD",],
			"UNI": ["BTC","EUR","USD",],
			"USDC": ["EUR","USD",],
			"XLM": ["BTC","EUR","GBP","USD",],
			"XRP": ["BTC","EUR","GBP","USD",],
		},
	},
	"bitbay-net": {
		"name": "BitBay",
		"url": "https://bitbay.net/",
		"api_url": "https://bitbay.net/API/Public/{crypto}{pair}/ticker.json",
		"getRateFromExchangeData": function(data, crypto, pair) {
			return data.ask
		},
		"pairs": {
			"BSV": ["BTC","EUR","PLN","USDT",],
			"BTC": ["EUR","GBP","PLN","USD","USDC","USDT",],
			"BTG": ["BTC","EUR","PLN","USDT",],
			"COMP": ["BTC","EUR","PLN","USDT",],
			"DASH": ["BTC","EUR","PLN","USDT",],
			"DOT": ["BTC","EUR","GBP","PLN","USDT",],
			"ETH": ["BTC","EUR","GBP","PLN","USD","USDC","USDT",],
			"GAME": ["BTC","EUR","PLN","USD",],
			"LINK": ["BTC","ETH","PLN","USDT",],
			"LSK": ["BTC","ETH","EUR","PLN","USDT",],
			"LTC": ["BTC","ETH","EUR","PLN","USD","USDT",],
			"LUNA": ["BTC","EUR","GBP","PLN","USDT",],
			"MKR": ["BTC","PLN",],
			"UNI": ["BTC","PLN","USDT",],
			"USDC": ["USD",],
			"USDT": ["PLN",],
			"XLM": ["BTC","ETH","EUR","PLN","USDT",],
			"XRP": ["BTC","ETH","EUR","GBP","PLN","USD","USDT",],
			"ZEC": ["BTC","EUR","PLN","USD","USDT",],
		},
	},
	"coinmate-io": {
		"name": "Coinmate",
		"url": "https://coinmate.io/",
		"api_url": "https://coinmate.io/api/ticker?currencyPair={crypto}_{pair}",
		"getRateFromExchangeData": function(data, crypto, pair) {
			return data.data.ask
		},
		"pairs": {
			"BCH": ["BTC","CZK","EUR",],
			"BTC": ["CZK","EUR",],
			"DASH": ["BTC","CZK","EUR",],
			"ETH": ["BTC","CZK","EUR",],
			"LTC": ["BTC","CZK","EUR",],
			"XRP": ["BTC","CZK","EUR",],
		},
	},
	"kraken-com": {
		"name": "Kraken",
		"url": "https://kraken.com/",
		"api_url": "https://api.kraken.com/0/public/Ticker?pair={crypto}{pair}",
		"getRateFromExchangeData": function(data, crypto, pair) {
			return data.result[Object.keys(data['result'])[0]].a[0]
		},
		"pairs": {
			"ADA": ["ETH","EUR","GBP","USD","USDT",],
			"ATOM": ["ETH","EUR","GBP","USD",],
			"BCH": ["ETH","EUR","GBP","JPY","USD","USDT",],
			"COMP": ["ETH","EUR","USD",],
			"DASH": ["EUR","USD",],
			"DOT": ["ETH","EUR","GBP","USD","USDT",],
			"ETC": ["ETH","EUR","USD",],
			"ETH": ["EUR","GBP","JPY","USD","USDC","USDT",],
			"EUR": ["GBP","JPY","USD",],
			"FIL": ["ETH","EUR","GBP","USD",],
			"GBP": ["USD",],
			"LINK": ["ETH","EUR","GBP","USD","USDT",],
			"LSK": ["ETH","EUR","USD",],
			"LTC": ["ETH","EUR","GBP","JPY","USD","USDT",],
			"MKR": ["EUR","GBP","USD",],
			"UNI": ["ETH","EUR","USD",],
			"USD": ["JPY",],
			"USDC": ["EUR","GBP","USD","USDT",],
			"USDT": ["EUR","GBP","JPY","USD",],
			"XLM": ["EUR","GBP","USD",],
			"XMR": ["EUR","USD",],
			"XRP": ["ETH","EUR","GBP","JPY","USD","USDT",],
			"ZEC": ["EUR","USD",],
		},
	},
}
