# abiword
# Autogenerated from man page /usr/lib/jvm/default/man/man1/abiword.1.gz
complete -c abiword -s g -l geometry --description 'Specifies window geometry at startup.'
complete -c abiword -s E -l plugin --description 'Execute the specified plugin instead of the main application.'
complete -c abiword -l import-extension --description 'Import the given file as if it had extension EXT, overriding automatic file t…'
complete -c abiword -s u -l userprofile --description 'Use PROFILE to read and store settings instead of the default   XDG_CONFIG_HO…'
complete -c abiword -s t -l to --description 'Convert the given file to another format, writing the result to R DEST .'
complete -c abiword -l to-name --description 'Only useful in conjunction with  --to= FORMAT .'
complete -c abiword -l verbose --description 'Set level of verbosity [0-2], 2 giving the most detailed output.'
complete -c abiword -s h -l help --description 'Display a short help message and exit.'
complete -c abiword -l version --description 'Report the version of AbiWord.'

