# alacritty
# Autogenerated from man page /usr/share/man/man1/alacritty.1.gz
complete -c alacritty -s h -l help --description 'Prints help information.'
complete -c alacritty -l hold --description 'Remain open after child process exits.'
complete -c alacritty -l live-config-reload --description 'Enable automatic config reloading.'
complete -c alacritty -l no-live-config-reload --description 'Disable automatic config reloading.'
complete -c alacritty -l persistent-logging --description 'Keep the log file after quitting Alacritty.'
complete -c alacritty -l print-events --description 'Print all events to stdout.'
complete -c alacritty -s q --description 'Reduces the level of verbosity (the min level is -qq).'
complete -c alacritty -l ref-test --description 'Generates ref test.'
complete -c alacritty -s v --description 'Increases the level of verbosity (the max level is -vvv).'
complete -c alacritty -s V -l version --description 'Prints version information OPTIONS.'
complete -c alacritty -l working-directory --description 'Start the shell in the specified working directory SEE ALSO See the alacritty…'

