# ansible-config
# Autogenerated from man page /usr/share/man/man1/ansible-config.1.gz
complete -c ansible-config -l version --description 'show program\'s version number, config file location, configured module search…'
complete -c ansible-config -s h -l help --description 'show this help message and exit.'
complete -c ansible-config -s v -l verbose --description 'verbose mode (-vvv for more, -vvvv to enable connection debugging) ACTIONS li…'
complete -c ansible-config -s c -l config --description 'path to configuration file, defaults to first file found in precedence.'
complete -c ansible-config -l only-changed --description 'Only show configurations that have changed from the default.'

