# ansible-vault
# Autogenerated from man page /usr/share/man/man1/ansible-vault.1.gz
complete -c ansible-vault -l version --description 'show program\'s version number, config file location, configured module search…'
complete -c ansible-vault -s h -l help --description 'show this help message and exit.'
complete -c ansible-vault -s v -l verbose --description 'verbose mode (-vvv for more, -vvvv to enable connection debugging) ACTIONS cr…'
complete -c ansible-vault -l ask-vault-pass --description 'ask for vault password.'
complete -c ansible-vault -l encrypt-vault-id --description 'the vault id used to encrypt (required if more than vault-id is provided).'
complete -c ansible-vault -l vault-id --description 'the vault identity to use.'
complete -c ansible-vault -l vault-password-file --description 'vault password file decrypt decrypt the supplied file using the provided vaul…'
complete -c ansible-vault -l output --description 'output file name for encrypt or decrypt; use - for stdout.'
complete -c ansible-vault -l stdin-name --description 'Specify the variable name for stdin.'
complete -c ansible-vault -s n -l name --description 'Specify the variable name.'
complete -c ansible-vault -s p -l prompt --description 'Prompt for the string to encrypt rekey re-encrypt a vaulted file with a new s…'
complete -c ansible-vault -l new-vault-id --description 'the new vault identity to use for rekey.'
complete -c ansible-vault -l new-vault-password-file --description 'new vault password file for rekey.'

