# ansible-galaxy
# Autogenerated from man page /usr/share/man/man1/ansible-galaxy.1.gz
complete -c ansible-galaxy -l version --description 'show program\'s version number, config file location, configured module search…'
complete -c ansible-galaxy -s h -l help --description 'show this help message and exit.'
complete -c ansible-galaxy -s v -l verbose --description 'verbose mode (-vvv for more, -vvvv to enable connection debugging) ACTIONS co…'

