# appletviewer
# Autogenerated from man page /usr/share/man/man1/appletviewer.1.gz
complete -c appletviewer -o debug --description 'Starts the applet viewer in the Java debugger, jdb(1), thus allowing you to d…'
complete -c appletviewer -o encoding --description 'Specify the input HTML file encoding name.'

