# asp
# Autogenerated from man page /usr/share/man/man1/asp.1.gz
complete -c asp -s a --description 'When relevant, specify an architecture other than that of the current host.'
complete -c asp -s f --description 'Allow files to be overwritten.'
complete -c asp -s h --description 'Print a short help text and exit.'
complete -c asp -s V --description 'Print a short version string and exit.'

