# aubiocut
# Autogenerated from man page /usr/share/man/man1/aubiocut.1.gz
complete -c aubiocut -s i -l input --description 'Run analysis on this audio file.'
complete -c aubiocut -s r -l samplerate --description 'Fetch the input source, resampled at the given sampling rate.'
complete -c aubiocut -s B -l bufsize --description 'The size of the buffer to analyze, that is the length of the window used for …'
complete -c aubiocut -s H -l hopsize --description 'The number of samples between two consecutive analysis.  Defaults to 256.'
complete -c aubiocut -s O -l onset --description 'The onset detection method to use.  See ONSET METHODS below.'
complete -c aubiocut -s b -l beat --description 'Use beat locations instead of onset locations.'
complete -c aubiocut -s t -l onset-threshold --description 'Set the threshold value for the onset peak picking.'
complete -c aubiocut -s c -l cut --description 'Cut input sound file at detected labels.'
complete -c aubiocut -s o -l output --description 'Specify the directory path where slices of the original source should be crea…'
complete -c aubiocut -l cut-until-nsamples --description 'How many extra samples should be added at the end of each slice (default 0).'
complete -c aubiocut -l cut-until-nslices --description 'How many extra slices should be added at the end of each slice (default 0).'
complete -c aubiocut -l create-first --description 'Alway create first slice.'
complete -c aubiocut -s h -l help --description 'Print a short help message and exit.'
complete -c aubiocut -s v -l verbose --description 'Be verbose.'
complete -c aubiocut -s q -l quiet --description 'Be quiet.  ONSET METHODS.'

