# aubiomfcc
# Autogenerated from man page /usr/share/man/man1/aubiomfcc.1.gz
complete -c aubiomfcc -s i -l input --description 'Run analysis on this audio file.'
complete -c aubiomfcc -s r -l samplerate --description 'Fetch the input source, resampled at the given sampling rate.'
complete -c aubiomfcc -s B -l bufsize --description 'The size of the buffer to analyze, that is the length of the window used for …'
complete -c aubiomfcc -s H -l hopsize --description 'The number of samples between two consecutive analysis.  Defaults to 256.'
complete -c aubiomfcc -s T -l timeformat --description 'Set time format (samples, ms, seconds).  Defaults to seconds.'
complete -c aubiomfcc -s h -l help --description 'Print a short help message and exit.'
complete -c aubiomfcc -s v -l verbose --description 'Be verbose.  REFERENCES.'

