# aubiotrack
# Autogenerated from man page /usr/share/man/man1/aubiotrack.1.gz
complete -c aubiotrack -s i -l input --description 'Run analysis on this audio file.'
complete -c aubiotrack -s o -l output --description 'Save results in this file.'
complete -c aubiotrack -s r -l samplerate --description 'Fetch the input source, resampled at the given sampling rate.'
complete -c aubiotrack -s B -l bufsize --description 'The size of the buffer to analyze, that is the length of the window used for …'
complete -c aubiotrack -s H -l hopsize --description 'The number of samples between two consecutive analysis.  Defaults to 256.'
complete -c aubiotrack -s s -l silence --description 'Set the silence threshold, in dB, under which the pitch will not be detected.'
complete -c aubiotrack -s m -l mix-input --description 'Mix source signal to the output signal before writing to sink.'
complete -c aubiotrack -s f -l force-overwrite --description 'Overwrite output file if it already exists.'
complete -c aubiotrack -s j -l jack --description 'Use Jack input/output.'
complete -c aubiotrack -s N -l miditap-note --description 'Override note value for MIDI tap.  Defaults to 69.'
complete -c aubiotrack -s V -l miditap-velop --description 'Override velocity value for MIDI tap.  Defaults to 65.'
complete -c aubiotrack -s T -l timeformat --description 'Set time format (samples, ms, seconds).  Defaults to seconds.'
complete -c aubiotrack -s h -l help --description 'Print a short help message and exit.'
complete -c aubiotrack -s v -l verbose --description 'Be verbose.  BEAT TRACKING METHODS.'

