# aubionotes
# Autogenerated from man page /usr/share/man/man1/aubionotes.1.gz
complete -c aubionotes -s i -l input --description 'Run analysis on this audio file.'
complete -c aubionotes -s r -l samplerate --description 'Fetch the input source, resampled at the given sampling rate.'
complete -c aubionotes -s B -l bufsize --description 'The size of the buffer to analyze, that is the length of the window used for …'
complete -c aubionotes -s H -l hopsize --description 'The number of samples between two consecutive analysis.  Defaults to 256.'
complete -c aubionotes -s O -l onset --description 'The onset detection method to use.  See ONSET METHODS below.'
complete -c aubionotes -s t -l onset-threshold --description 'Set the threshold value for the onset peak picking.'
complete -c aubionotes -s M -l minioi --description 'Set the minimum inter-onset interval, in seconds, the shortest interval betwe…'
complete -c aubionotes -s p -l pitch --description 'The pitch detection method to use.  See PITCH METHODS below.'
complete -c aubionotes -s u -l pitch-unit --description 'The unit to be used to print frequencies.'
complete -c aubionotes -s l -l pitch-tolerance --description 'Set the tolerance for the pitch detection algorithm.'
complete -c aubionotes -s s -l silence --description 'Set the silence threshold, in dB, under which the pitch will not be detected.'
complete -c aubionotes -s d -l release-drop --description 'Set the release drop threshold, in dB.'
complete -c aubionotes -s T -l timeformat --description 'Set time format (samples, ms, seconds).  Defaults to seconds.'
complete -c aubionotes -s j -l jack --description 'Use Jack input/output.'
complete -c aubionotes -s h -l help --description 'Print a short help message and exit.'
complete -c aubionotes -s v -l verbose --description 'Be verbose.  ONSET METHODS.'

