# aucat
# Autogenerated from man page /usr/share/man/man1/aucat.1.gz
complete -c aucat -s b --description 'The buffer size of the audio device in frames.  Default is 7680.'
complete -c aucat -s c --description 'The range of audio file channel numbers.  The default is 0:1, i. e.  stereo.'
complete -c aucat -s d --description 'Increase log verbosity.'
complete -c aucat -s e --description 'Encoding of the audio file.  The default is s16.'
complete -c aucat -s f --description 'Use this sndio 7 audio device.'
complete -c aucat -s g --description 'Go to the given time position and start playback or recording there.'
complete -c aucat -s h --description 'Audio file type.'
complete -c aucat -s i --description 'Play this audio file.'
complete -c aucat -s j --description 'Control whether source channels are joined or expanded if they don\'t match th…'
complete -c aucat -s n --description 'Off-line mode.'
complete -c aucat -s o --description 'Record into this audio file.'
complete -c aucat -s p --description 'Time offset where the beginning of the file belongs.'
complete -c aucat -s q --description 'Control audio device properties through this MIDI port.'
complete -c aucat -s r --description 'Sample rate in Hertz of the audio file.  The default is 48000.'
complete -c aucat -s v --description 'Software volume attenuation of the file to play.'

