# audacious
# Autogenerated from man page /usr/share/man/man1/audacious.1.gz
complete -c audacious -s h -l help --description 'Show a brief list of options. SS Opening files:.'
complete -c audacious -s e -l enqueue --description 'Add the files on the command line to the current playlist but do not start pl…'
complete -c audacious -s E -l enqueue-to-temp --description 'Add the files on the command line to the ``Now Playing\'\' playlist and start p…'
complete -c audacious -s p -l play --description 'Start playback.   If paused, playback will resume from the same point.'
complete -c audacious -s u -l pause --description 'Pause playback, or resume if already paused.'
complete -c audacious -s t -l play-pause --description 'Equivalent to --pause if playback is active, otherwise --play.'
complete -c audacious -s s -l stop --description 'Stop playback.'
complete -c audacious -s r -l rew --description 'Skip to the previous song in the playlist.'
complete -c audacious -s f -l fwd --description 'Skip to the next song in the playlist. SS Miscellaneous:.'
complete -c audacious -s m -l show-main-window --description 'Show the Audacious window if it is hidden and bring it to the top.'
complete -c audacious -s j -l show-jump-box --description 'Show the Jump to Song window.'
complete -c audacious -s H -l headless --description 'Start in command-line mode; i. e. , without any graphical user interface.'
complete -c audacious -s q -l quit-after-play --description 'Exit as soon as playback stops, or immediately if there is nothing to play.'
complete -c audacious -s v -l version --description 'Print version information and exit.'
complete -c audacious -s V -l verbose --description 'Print debugging output while running (may be used twice for even more output).'
complete -c audacious -s N -l new-instance --description 'Starts a new instance.'

