# bluefish
# Autogenerated from man page /usr/share/man/man1/bluefish.1.gz
complete -c bluefish -s c -l curwindow --description 'Open a file in an existing window.'
complete -c bluefish -s n -l newwindow --description 'Open a file in a new window.'
complete -c bluefish -s '?' -l help -l 'help-*' -l help-all --description 'Print all or just a group of help options.'
complete -c bluefish -s v -l Version --description 'Print version information.'

