# bmaptool
# Autogenerated from man page /usr/share/man/man1/bmaptool.1.gz
complete -c bmaptool -l version --description '.'
complete -c bmaptool -s h -l help --description '.'
complete -c bmaptool -s q -l quiet --description '.'
complete -c bmaptool -s d -l debug --description '.'
complete -c bmaptool -l bmap --description '.'
complete -c bmaptool -l bmap-sig --description '.'
complete -c bmaptool -l nobmap --description '.'
complete -c bmaptool -l no-verify --description '.'
complete -c bmaptool -l no-sig-verify --description '.'
complete -c bmaptool -s o -l output --description '.'
complete -c bmaptool -l no-checksum --description '.'

