# bookman
# Autogenerated from man page /usr/share/man/man1/bookman.1.gz
complete -c bookman -s p --description 'PDF output format.'
complete -c bookman -s P --description 'Postscript output format.'
complete -c bookman -s x --description 'X11 previewing, using gxditview(1).'
complete -c bookman -s n --description 'no format, output is direct gtroff intermediate format.'
complete -c bookman -s o --description 'Output in file outfile.  Default is standard output.'
complete -c bookman -s a --description 'Set the author, on the cover page.'
complete -c bookman -s d --description 'Set the date on the cover page.'
complete -c bookman -s r --description 'Set the book name and release on the cover page.'
complete -c bookman -s t --description 'Set the title on the cover page.'
complete -c bookman -s v --description 'Specify the name of the volume.'
complete -c bookman -s c --description 'Uses the file coverfile to generate the cover page, i. e.'

