# catfish
# Autogenerated from man page /usr/share/man/man1/catfish.1.gz
complete -c catfish -l version --description 'Show the version number and exit.'
complete -c catfish -s h -l help --description 'Show the help message and exit.'
complete -c catfish -s v -l verbose --description 'Show debug messages (-vv will also debug catfish_lib).'
complete -c catfish -l large-icons --description 'Use large icons.'
complete -c catfish -l thumbnails --description 'Use thumbnails.'
complete -c catfish -l iso-time --description 'Display time in ISO format.'
complete -c catfish -l path --description 'Set the default search path.'
complete -c catfish -l exact --description 'Perform exact match.'
complete -c catfish -l hidden --description 'Include hidden files.'
complete -c catfish -l fulltext --description 'Perform fulltext search.'
complete -c catfish -l start --description 'If path and query are provided, start searching when the application is displ…'

