# ceph-mds
# Autogenerated from man page /usr/share/man/man8/ceph-mds.8.gz
complete -c ceph-mds -s f -l foreground --description 'Foreground: do not daemonize after startup (run in foreground).'
complete -c ceph-mds -s d --description 'Debug mode: like -f, but also send all log output to stderr.'
complete -c ceph-mds -l setuser --description 'Set uid after starting.'
complete -c ceph-mds -l setgroup --description 'Set gid after starting.'
complete -c ceph-mds -s c -l conf --description 'Use ceph. conf configuration file instead of the default /etc/ceph/ceph.'
complete -c ceph-mds -s m --description 'Connect to specified monitor (instead of looking through ceph. conf).'
complete -c ceph-mds -l id/-i --description 'Set ID portion of the MDS name.'

