# ceph-conf
# Autogenerated from man page /usr/share/man/man8/ceph-conf.8.gz
complete -c ceph-conf -s c --description 'the Ceph configuration file.'
complete -c ceph-conf -l filter-key --description 'filter section list to only include sections with given key defined.'
complete -c ceph-conf -l filter-key-value --description 'filter section list to only include sections with given key/value pair.'
complete -c ceph-conf -l name --description 'the Ceph name in which the sections are searched (default \\(aqclient.'
complete -c ceph-conf -s r -l resolve-search --description 'search for the first file that exists and can be opened in the resulted comma…'
complete -c ceph-conf -s s -l section --description 'additional sections to search.'
complete -c ceph-conf -s L -l list-all-sections --description 'list all sections in the configuration file.'
complete -c ceph-conf -s l -l list-sections --description 'list the sections with the given prefix.'
complete -c ceph-conf -l lookup --description 'search and print the specified configuration setting.'
complete -c ceph-conf -s h -l help --description 'print a summary of usage.'

