# ceph-clsinfo
# Autogenerated from man page /usr/share/man/man8/ceph-clsinfo.8.gz
complete -c ceph-clsinfo -s n -l name --description 'Shows the class name.'
complete -c ceph-clsinfo -s v -l version --description 'Shows the class version.'
complete -c ceph-clsinfo -s a -l arch --description 'Shows the class architecture.'

