# ceph-syn
# Autogenerated from man page /usr/share/man/man8/ceph-syn.8.gz
complete -c ceph-syn -s d --description 'Detach from console and daemonize after startup.'
complete -c ceph-syn -s c -l conf --description 'Use ceph. conf configuration file instead of the default /etc/ceph/ceph.'
complete -c ceph-syn -s m --description 'Connect to specified monitor (instead of looking through ceph. conf).'
complete -c ceph-syn -l num_client --description 'Run num different clients, each in a separate thread.'
complete -c ceph-syn -l syn --description 'Run the given workload.  May be specified as many times as needed.'

