# ceph-mon
# Autogenerated from man page /usr/share/man/man8/ceph-mon.8.gz
complete -c ceph-mon -s f -l foreground --description 'Foreground: do not daemonize after startup (run in foreground).'
complete -c ceph-mon -s d --description 'Debug mode: like -f, but also send all log output to stderr.'
complete -c ceph-mon -l setuser --description 'Set uid after starting.'
complete -c ceph-mon -l setgroup --description 'Set gid after starting.'
complete -c ceph-mon -s c -l conf --description 'Use ceph. conf configuration file instead of the default /etc/ceph/ceph.'
complete -c ceph-mon -l mkfs --description 'Initialize the mon data directory with seed information to form and initial c…'
complete -c ceph-mon -l keyring --description 'Specify a keyring for use with --mkfs.'

