# ceph-debugpack
# Autogenerated from man page /usr/share/man/man8/ceph-debugpack.8.gz
complete -c ceph-debugpack -s c -l conf --description 'Use ceph. conf configuration file instead of the default /etc/ceph/ceph.'

