# ceph-fuse
# Autogenerated from man page /usr/share/man/man8/ceph-fuse.8.gz
complete -c ceph-fuse -s o --description 'Mount options.'
complete -c ceph-fuse -s d --description 'Run in foreground, send all log output to stderr and enable FUSE debugging (-…'
complete -c ceph-fuse -s c -l conf --description 'Use ceph. conf configuration file instead of the default /etc/ceph/ceph.'
complete -c ceph-fuse -s m --description 'Connect to specified monitor (instead of looking through ceph. conf).'
complete -c ceph-fuse -s k --description 'Provide path to keyring; useful when it\\(aqs absent in standard locations.'
complete -c ceph-fuse -l client_mountpoint/-r --description 'Use root_directory as the mounted root, rather than the full Ceph tree.'
complete -c ceph-fuse -s f --description 'Foreground: do not daemonize after startup (run in foreground).'
complete -c ceph-fuse -s s --description 'Disable multi-threaded operation.'

