# ceph-post-file
# Autogenerated from man page /usr/share/man/man8/ceph-post-file.8.gz
complete -c ceph-post-file -s d -l description --description 'Add a short description for the upload.'
complete -c ceph-post-file -s u --description 'Set the user metadata for the upload.'

