# ceph-authtool
# Autogenerated from man page /usr/share/man/man8/ceph-authtool.8.gz
complete -c ceph-authtool -s l -l list --description 'will list all keys and capabilities present in the keyring.'
complete -c ceph-authtool -s p -l print-key --description 'will print an encoded key for the specified entityname.'
complete -c ceph-authtool -s C -l create-keyring --description 'will create a new keyring, overwriting any existing keyringfile.'
complete -c ceph-authtool -s g -l gen-key --description 'will generate a new secret key for the specified entityname.'
complete -c ceph-authtool -l gen-print-key --description 'will generate a new secret key for the specified entityname, without altering…'
complete -c ceph-authtool -l import-keyring --description 'will import the content of a given keyring to the keyringfile.'
complete -c ceph-authtool -s n -l name --description 'specify entityname to operate on.'
complete -c ceph-authtool -s a -l add-key --description 'will add an encoded key to the keyring.'
complete -c ceph-authtool -l cap --description 'will set the capability for given subsystem.'
complete -c ceph-authtool -l caps --description 'NDENT 7. 0 NDENT 3.'
complete -c ceph-authtool -l mode --description 'will set the desired file mode to the keyring e. g: 0644, defaults to 0600.'

