# ceph-bluestore-tool
# Autogenerated from man page /usr/share/man/man8/ceph-bluestore-tool.8.gz
complete -c ceph-bluestore-tool -l dev --description 'Add device to the list of devices to consider.'
complete -c ceph-bluestore-tool -l devs-source --description 'Add device to the list of devices to consider as sources for migrate operatio…'
complete -c ceph-bluestore-tool -l dev-target --description 'Specify target device migrate operation or device to add for adding new DB/WA…'
complete -c ceph-bluestore-tool -l path --description 'Specify an osd path.'
complete -c ceph-bluestore-tool -l out-dir --description 'Output directory for bluefs-export.'
complete -c ceph-bluestore-tool -s l -l log-file --description 'file to log to.'
complete -c ceph-bluestore-tool -l log-level --description 'debug log level.'
complete -c ceph-bluestore-tool -l deep --description 'deep scrub/repair (read and validate object data, not just metadata).'
complete -c ceph-bluestore-tool -l allocator --description 'Useful for free-dump and free-score actions.  Selects allocator(s).'

