# ceph-volume
# Autogenerated from man page /usr/share/man/man8/ceph-volume.8.gz
complete -c ceph-volume -l report --description '.'
complete -c ceph-volume -l data --description 'A logical group name or a path to a logical volume For encrypting an OSD, the…'

