# ceph-create-keys
# Autogenerated from man page /usr/share/man/man8/ceph-create-keys.8.gz
complete -c ceph-create-keys -l cluster --description 'name of the cluster (default \\(aqceph\\(aq).'
complete -c ceph-create-keys -s t --description 'time out after seconds (default: 600) waiting for a response from the monitor.'
complete -c ceph-create-keys -s i -l id --description 'id of a ceph-mon that is coming up.'
complete -c ceph-create-keys -s v -l verbose --description 'be more verbose.'

