# chezdav
# Autogenerated from man page /usr/share/man/man1/chezdav.1.gz
complete -c chezdav -s d -l htdigest --description 'Path to a htdigest file, to protect server with DIGEST method.'
complete -c chezdav -s P -l path --description 'Path to export.'
complete -c chezdav -s p -l port --description 'Port to listen from.  By default, a port is allocated randomly.'
complete -c chezdav -s v -l verbose --description 'Verbosely print running information.'
complete -c chezdav -l version --description 'Print program version number.'

