# chirpw
# Autogenerated from man page /usr/share/man/man1/chirpw.1.gz
complete -c chirpw -l help --description 'Show summary of options.'
complete -c chirpw -l profile --description 'Enable Profiling.  AUTHOR chirpw was written by Dan Smith.'

