# darktable-cli
# Autogenerated from man page /usr/share/man/man1/darktable-cli.1.gz
complete -c darktable-cli -l width --description 'This optional parameter allows one to limit the width of the exported image t…'
complete -c darktable-cli -l height --description 'This optional parameter allows one to limit the height of the exported image …'
complete -c darktable-cli -l bpp --description 'An optional parameter to define the bit depth of the exported image; allowed …'
complete -c darktable-cli -l hq --description 'A flag that defines whether to use high quality resampling during export.'
complete -c darktable-cli -l upscale --description 'A flag that defines whether to allow upscaling during export.'
complete -c darktable-cli -l style --description 'Specify the name of a style to be applied during export.'
complete -c darktable-cli -l style-overwrite --description 'The specified style overwrites the history stack instead of being appended to…'
complete -c darktable-cli -l apply-custom-presets --description 'With this option you can decide if darktable loads its set of default paramet…'
complete -c darktable-cli -l verbose --description 'Enables verbose output.'

