# dnssort
# Autogenerated from man page /usr/share/man/man1/dnssort.1.gz
complete -c dnssort -l help --description 'Display some help and exit.'
complete -c dnssort -s r --description 'Reverse the sorting comparisons.'
complete -c dnssort -l version --description 'Display program version and license and exit.'

