# empathy-accounts
# Autogenerated from man page /usr/share/man/man1/empathy-accounts.1.gz
complete -c empathy-accounts -s h -l hidden --description 'Don\'t display any dialogs; do any work (eg, importing) and exit.'
complete -c empathy-accounts -s n -l if-needed --description 'Don\'t display any dialogs if there are any non-salut accounts.'
complete -c empathy-accounts -s s --description '.'
complete -c empathy-accounts -l select-account --description 'Initially select given account (eg, gabble/jabber/foo_40example_2eorg0) AUTHO…'

