# epiphany
# Autogenerated from man page /usr/share/man/man1/epiphany.1.gz
complete -c epiphany -l new-window --description 'Open a new browser window instead of a new tab.'
complete -c epiphany -s l -l load-session --description 'Load the given session state file.'
complete -c epiphany -s i -l incognito-mode --description 'Start an instance with user data read-only.'
complete -c epiphany -s p -l private-instance --description 'Start a private instance with separate user data.'
complete -c epiphany -s a -l application-mode --description 'Start a private instance in web application mode (requires passing either des…'
complete -c epiphany -l automation-mode --description 'Start a private instance for WebDriver control.'
complete -c epiphany -l profile --description 'Custom profile directory for private instance (optional).'
complete -c epiphany -s '?' -l help --description 'Show help options.'
complete -c epiphany -l version --description 'Show version.'

