# evolution
# Autogenerated from man page /usr/share/man/man1/evolution.1.gz
complete -c evolution -s c -l component --description 'Start Evolution showing the specified component.'
complete -c evolution -s g -l geometry --description 'Apply the given geometry to the main window.'
complete -c evolution -l offline --description 'Start in offline mode.'
complete -c evolution -l online --description 'Start in online mode.'
complete -c evolution -l force-online --description 'Ignore network availability.'
complete -c evolution -l disable-eplugin --description 'Disable loading of any plugins.'
complete -c evolution -l disable-preview --description 'Disable preview pane of Mail, Contacts and Tasks.'
complete -c evolution -s i -l import --description 'Import URIs or filenames given as rest of arguments.'

