# flickcurl
# Autogenerated from man page /usr/share/man/man1/flickcurl.1.gz
complete -c flickcurl -s a -l auth --description 'Authenticate with a FROB and update the authentication file.'
complete -c flickcurl -s d -l delay --description 'Set delay between requests to DELAY milliseconds.'
complete -c flickcurl -s h -l help --description 'Show summary of options and exit.'
complete -c flickcurl -s o -l output --description 'Write the results of format feed API calls to FILE.'
complete -c flickcurl -s q -l quiet --description 'Display less information while the program runs.'
complete -c flickcurl -s v -l version --description 'Display the version of the program and exit.'
complete -c flickcurl -s V -l verbose --description 'Display more information while the program runs.  COMMANDS.'

