# flickrdf
# Autogenerated from man page /usr/share/man/man1/flickrdf.1.gz
complete -c flickrdf -s h -l help --description 'Show summary of options and exit.'
complete -c flickrdf -s v -l version --description 'Display the version of the program and exit.'
complete -c flickrdf -s d -l delay --description 'Set delay between requests to DELAY milliseconds.'
complete -c flickrdf -s D -l debug --description 'Print lots of debugging output.'
complete -c flickrdf -s o -l output --description 'Set output format to FORMAT.'

