# flickcurl-config
# Autogenerated from man page /usr/share/man/man1/flickcurl-config.1.gz
complete -c flickcurl-config -l prefix --description 'Get the flickcurl installation prefix.'
complete -c flickcurl-config -l libs --description 'Print library linking information.'
complete -c flickcurl-config -l private-libs --description 'Print library private/static linking information.'
complete -c flickcurl-config -l cflags --description 'Print pre-processor and compiler flags.'
complete -c flickcurl-config -l help --description 'display this help and exit.'
complete -c flickcurl-config -l version --description 'output version information.'
complete -c flickcurl-config -l version-decimal --description 'Output version as a decimal integer.'

