# foo2zjs-icc2ps
# Autogenerated from man page /usr/share/man/man1/foo2zjs-icc2ps.1
complete -c foo2zjs-icc2ps -s b --description 'Black point compensation (CRD only).'
complete -c foo2zjs-icc2ps -s c --description 'Precision (0=LowRes, 1=Normal (default), 2=Hi-res) (CRD only).'
complete -c foo2zjs-icc2ps -s i --description 'Input profile: Generates Color Space Array (CSA).'
complete -c foo2zjs-icc2ps -s n --description 'Alternate way to set precision, number of CLUT points (CRD only).'
complete -c foo2zjs-icc2ps -s o --description '.'
complete -c foo2zjs-icc2ps -s t --description 'Intent (0=Perceptual, 1=Colorimetric, 2=Saturation, 3=Absolute).'
complete -c foo2zjs-icc2ps -s u --description 'Do NOT generate resource name on CRD.'

