# foomatic-kitload
# Autogenerated from man page /usr/share/man/man8/foomatic-kitload.8.gz
complete -c foomatic-kitload -s k --description 'option, where dirname is the toplevel directory of a foomatic driver "kit".'
complete -c foomatic-kitload -s d --description 'destdir is a prefix to prepend to the install path.'

