# fsarchiver
# Autogenerated from man page /usr/share/man/man8/fsarchiver.8.gz
complete -c fsarchiver -s h -l help --description 'Show help and information about how to use fsarchiver with examples.'
complete -c fsarchiver -s V -l version --description 'Show program version and exit.'
complete -c fsarchiver -s v -l verbose --description 'Verbose mode (can be used several times to increase the level of details).'
complete -c fsarchiver -s o -l overwrite --description 'Overwrite the archive if it already exists instead of failing.'
complete -c fsarchiver -s d -l debug --description 'Debug mode (can be used several times to increase the level of details).'
complete -c fsarchiver -s x -l experimental --description 'Allow to save filesystems which support is considered experimental in fsarchi…'
complete -c fsarchiver -s A -l allow-rw-mounted --description 'Allow to save a filesystem which is mounted in read-write (live backup).'
complete -c fsarchiver -s a -l allow-no-acl-xattr --description 'Allow to save a filesystem when ACLs and extended attributes are not supporte…'
complete -c fsarchiver -s e -l exclude --description 'Exclude files and directories that match specified pattern.'
complete -c fsarchiver -s L -l label --description 'Set the label of the archive: it is just a comment about its contents.'
complete -c fsarchiver -s z -l compress --description 'Legacy compression levels are between 0 (very fast) and 9 (very good).'
complete -c fsarchiver -s Z -l zstd --description 'Zstd compression levels are between 1 (very fast) and 22 (very good).'
complete -c fsarchiver -s s -l split --description 'Split the archive into several files of mbsize megabytes each.'
complete -c fsarchiver -s j -l jobs --description 'Create more than one (de)compression thread.  Useful on multi-core CPUs.'

