# gdome-config
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gdome-config.1.gz
complete -c gdome-config -l version --description 'Print the currently installed version of gdome2 on the standard output.'
complete -c gdome-config -l libs --description 'Print the linker flags that are necessary to link a gdome2 program.'
complete -c gdome-config -l cflags --description 'Print the compiler flags that are necessary to compile a gdome2 program.'
complete -c gdome-config -l prefix --description 'If specified, use DIR instead of the installation prefix that gdome2 was bui…'
complete -c gdome-config -l exec-prefix --description 'If specified, use DIR instead of the installation exec prefix that gdome2 wa…'
complete -c gdome-config -l help --description 'Print a short help text and exit.'

