# gig2stereo
# Autogenerated from man page /usr/share/man/man1/gig2stereo.1.gz
complete -c gig2stereo -l force-replace --description 'Force replacing any found old mono sample reference by the new true stereo sa…'
complete -c gig2stereo -l incompatible --description 'Also match incompatible mono samples as pairs.'
complete -c gig2stereo -l keep --description 'Keep old mono samples.'
complete -c gig2stereo -s r --description 'Recurse through subdirectories.'
complete -c gig2stereo -s v --description 'Print version and exit.'

