# gigolo
# Autogenerated from man page /usr/share/man/man1/gigolo.1.gz
complete -c gigolo -s a -l auto-connect --description 'Connect all bookmarks which are marked as \'auto connect\' and exit.'
complete -c gigolo -s i -l new-instance --description 'Don\'t find and show an already running instance of Gigolo, instead force open…'
complete -c gigolo -s l -l list-schemes --description 'Print a list of supported URI schemes and exit.'
complete -c gigolo -s v -l verbose --description 'Be verbose and print some more information to stdout.'
complete -c gigolo -s V -l version --description 'Show version information.'

