# gitg
# Autogenerated from man page /usr/share/man/man1/gitg.1.gz
complete -c gitg -s h -l help --description 'Show help options.'
complete -c gitg -l help-all --description 'Show all help options.'
complete -c gitg -l help-gtk --description 'Show GTK+ Options . PP Application Options:.'
complete -c gitg -s v -l version --description 'Show the application?s version.'
complete -c gitg -l activity --description 'Start gitg with a particular activity.'
complete -c gitg -s c -l commit --description 'Start gitg with the commit activity (shorthand for --activity commit).'
complete -c gitg -l no-wd --description 'Do not try to load a repository from the current working directory.'
complete -c gitg -l standalone --description 'Run gitg in standalone mode.'
complete -c gitg -l display --description 'X display to use.'
complete -c gitg -s a -l all --description 'Select all commits by default in the history activity.'
complete -c gitg -s b -l branches --description 'Select all branches by default in the history activity.'
complete -c gitg -s r -l remotes --description 'Select all remotes by default in the history activity.'
complete -c gitg -s t -l tags --description 'Select all tags by default in the history activity.'
complete -c gitg -s s -l select-reference --description 'Select the specified reference by default in the history activity.'

