# gnome-2048
# Autogenerated from man page /usr/share/man/man6/gnome-2048.6.gz
complete -c gnome-2048 -l cli --description 'Play in the terminal.  See â--cli=helpâ for documentation.'
complete -c gnome-2048 -s s -l size --description 'Changes the size of the grid.'
complete -c gnome-2048 -s v -l version --description 'Prints the program version and exits.'

