# gnome-software
# Autogenerated from man page /usr/share/man/man1/gnome-software.1.gz
complete -c gnome-software -s '?' -l help --description 'Prints a short help text and exits.'
complete -c gnome-software -l version --description 'Prints the program version and exits.'
complete -c gnome-software -l mode --description 'Starts gnome-software in the given mode.'

