# gnome-dictionary
# Autogenerated from man page /usr/share/man/man1/gnome-dictionary.1.gz
complete -c gnome-dictionary -l look-up --description 'Looks up the specified WORD using the default dictionary source, or the one s…'
complete -c gnome-dictionary -l match --description 'List all the entries in the dictionary source that match the specified WORD.'
complete -c gnome-dictionary -l source -s s --description 'Specifies the dictionary source to be used for looking up or matching words.'
complete -c gnome-dictionary -l database -s D --description 'Specifies the database in the dictionary source to be used for looking up or …'
complete -c gnome-dictionary -l strategy -s S --description 'Specifies the matching strategy in the dictionary source to be used for looki…'

