# gsimplecal
# Autogenerated from man page /usr/share/man/man1/gsimplecal.1.gz
complete -c gsimplecal -s v -l version --description 'Print the program name and version to stdout, then exit with code 0.'
complete -c gsimplecal -s h -l help --description 'Print the short usage help to stderr, then exit with error code 2.'

