# hardinfo
# Autogenerated from man page /usr/share/man/man1/hardinfo.1.gz
complete -c hardinfo -s h -l help --description 'Show help options.'
complete -c hardinfo -s r -l generate-report --description 'creates a report and prints to standard output.'
complete -c hardinfo -s f -l report-format --description 'chooses a report format (text, html).'
complete -c hardinfo -s b -l run-benchmark --description 'run benchmark; requires benchmark. so to be loaded.'
complete -c hardinfo -s l -l list-modules --description 'lists modules.'
complete -c hardinfo -s m -l load-module --description 'specify module to load.'
complete -c hardinfo -s a -l autoload-deps --description 'automatically load module dependencies.'
complete -c hardinfo -s v -l version --description 'shows program version and quit AUTHORS/CONTRIBUTORS For current maintainers c…'

