# heif-convert
# Autogenerated from man page /usr/share/man/man1/heif-convert.1.gz
complete -c heif-convert -s q --description 'Defines quality level between 0 and 100 for the generated output file.'

