# heif-enc
# Autogenerated from man page /usr/share/man/man1/heif-enc.1.gz
complete -c heif-enc -o qQUALITY -l qualityQUALITY --description 'Defines quality level between 0 and 100 for the generated output file.'
complete -c heif-enc -s L -l lossless --description 'Generate lossless output (-q has no effect).'
complete -c heif-enc -o tSIZE -l thumbSIZE --description 'Generate thumbnail with maximum size SIZE pixels (default: off).'
complete -c heif-enc -l no-alpha --description 'Do not save alpha channel.'
complete -c heif-enc -l no-thumb-alpha --description 'Do not save alpha channel in thumbnail image.'
complete -c heif-enc -o oFILENAME -l outputFILENAME --description 'Output filename (optional).'
complete -c heif-enc -s v -l verbose --description 'Enable logging output (more -v will increase logging level).'
complete -c heif-enc -s P -l params --description 'Show all encoder parameters.'
complete -c heif-enc -o bDEPTH --description 'Bit-depth of generated HEIF file when using 16-bit PNG input (default: 10 bit…'
complete -c heif-enc -s q -l quality --description 'Defines quality level between 0 and 100 for the generated output file.'
complete -c heif-enc -s t -l thumb --description 'Generate thumbnail with maximum size SIZE pixels (default: off).'
complete -c heif-enc -s o -l output --description 'Output filename (optional).'
complete -c heif-enc -s b --description 'Bit-depth of generated HEIF file when using 16-bit PNG input (default: 10 bit…'
complete -c heif-enc -s p --description 'Set additional encoder parameters.  See NOTES below.  EXIT STATUS.'

