# heif-thumbnailer
# Autogenerated from man page /usr/share/man/man1/heif-thumbnailer.1.gz
complete -c heif-thumbnailer -s s --description 'Defines the maximum width and height of the thumbnail to generate.'

