# hydrogen
# Autogenerated from man page /usr/share/man/man1/hydrogen.1.gz
complete -c hydrogen -s P -l data --description '.'
complete -c hydrogen -s d -l driver --description '.'
complete -c hydrogen -s s -l song --description '.'
complete -c hydrogen -s S -l jacksessionid --description '.'
complete -c hydrogen -s p -l playlist --description '.'
complete -c hydrogen -s k -l kit --description '.'
complete -c hydrogen -s i -l install --description '.'
complete -c hydrogen -s n -l nosplash --description '.'
complete -c hydrogen -s V -l verbose --description 'Level, if present, may be None, Error, Warning, Info, Debug or 0xHHHH.'
complete -c hydrogen -s v -l version --description '.'
complete -c hydrogen -s h -l help --description 'FILES.'

