# idnconv2
# Autogenerated from man page /usr/share/man/man1/idnconv2.1.gz
complete -c idnconv2 -o in -s i --description 'Specify the encoding name of the input text.'
complete -c idnconv2 -o out -s o --description 'Specify the encoding name of the output text.'
complete -c idnconv2 -o conf -s c --description 'Specify the path of idnkit configuration file.'
complete -c idnconv2 -o noconf -s C --description 'Suppress reading a configuration file.'
complete -c idnconv2 -o reverse -s r --description 'Specify decoder mode.  idnconv2 runs in encoder mode, by default.'
complete -c idnconv2 -o registration -s g --description 'Use domain name registration protocol.  This is the default behavior.'
complete -c idnconv2 -o lookup -s l --description 'Use domain name lookup protocol.'
complete -c idnconv2 -o nomap -s M --description 'Don\'t perform the ``map\'\' action.  This is the same as ``-skip map\'\'.'
complete -c idnconv2 -o skip --description 'Skip actions.  the following action names are recognized: . RS 4.'
complete -c idnconv2 -o whole -s w --description 'Assumes each input line represents an internationalized domain name.'
complete -c idnconv2 -o localcheck -s e --description 'Also perform local code point check using file.'
complete -c idnconv2 -o flush --description 'Force line-buffering mode.'
complete -c idnconv2 -o test -s t --description 'Print which language, input encoding and output encoding will be chosen, if t…'
complete -c idnconv2 -o version -s v --description 'Print version information and quit.'
complete -c idnconv2 -o help -s h --description 'Print help and quit.'

