# idncheck
# Autogenerated from man page /usr/share/man/man1/idncheck.1.gz
complete -c idncheck -o in -s i --description 'Specify the encoding name of the domain name specified as an argument.'
complete -c idncheck -o conf -s c --description 'Specify the path of idnkit configuration file.'
complete -c idncheck -o noconf -s C --description 'Suppress reading a configuration file.'
complete -c idncheck -o registration -s g --description 'Use domain name registration protocol.  This is the default behavior.'
complete -c idncheck -o lookup -s l --description 'Use domain name lookup protocol.'
complete -c idncheck -o nomap -s M --description 'Don\'t perform the ``map\'\' action.  This is the same as ``-skip map\'\'.'
complete -c idncheck -o skip --description 'Skip actions.  the following action names are recognized: . RS 4.'
complete -c idncheck -o localcheck -s e --description 'Also perform code point check using file.'
complete -c idncheck -o quiet -s q --description 'Suppress a result message; yield exit status only.'
complete -c idncheck -o test -s t --description 'Print which language, input encoding and output encoding will be chosen if th…'
complete -c idncheck -o version -s v --description 'Print version information and quit.'
complete -c idncheck -o help -s h --description 'Print help and quit.'

