# idncmp
# Autogenerated from man page /usr/share/man/man1/idncmp.1.gz
complete -c idncmp -o in -s i --description 'Specify the encoding name of the domain names specified as arguments.'
complete -c idncmp -o conf -s c --description 'Specify the path of idnkit configuration file.'
complete -c idncmp -o noconf -s C --description 'Suppress reading a configuration file.'
complete -c idncmp -o registration -s g --description 'Use domain name registration protocol.'
complete -c idncmp -o lookup -s l --description 'Use domain name lookup protocol.  This is the default behavior.'
complete -c idncmp -o nomap -s M --description 'Don\'t perform the ``map\'\' action.  This is the same as ``-skip map\'\'.'
complete -c idncmp -o skip --description 'Skip actions.  the following action names are recognized: . RS 4.'
complete -c idncmp -o localcheck -s e --description 'Also perform local code point check using file.'
complete -c idncmp -o quiet -s q --description 'Suppress a result message; yield exit status only.'
complete -c idncmp -o test -s t --description 'Print which language, input encoding and output encoding will be chosen if th…'
complete -c idncmp -o version -s v --description 'Print version information and quit.'
complete -c idncmp -o help -s h --description 'Print help and quit.'

