# ircat
# Autogenerated from man page /usr/share/man/man1/ircat.1.gz
complete -c ircat -s h -l help --description 'Display usage summary.'
complete -c ircat -s v -l version --description 'Display version.'
complete -c ircat -s c -l config --description 'Set config file.  EXAMPLES If .'

