# irexec
# Autogenerated from man page /usr/share/man/man1/irexec.1.gz
complete -c irexec -s h -l help --description 'Display usage summary.'
complete -c irexec -s v -l version --description 'Display version.'
complete -c irexec -s d -l daemon --description 'Make irexec fork to background.'
complete -c irexec -s D -l loglevel --description 'Determine the amount of logging information.'
complete -c irexec -s n -l name --description 'Use this program name instead of the default irexec as identifier in the lirc…'

