# irpipe
# Autogenerated from man page /usr/share/man/man1/irpipe.1.gz
complete -c irpipe -s d -l device --description 'Set kernel device, default is /dev/irpipe0.'
complete -c irpipe -s b -l bin2text --description 'Convert binary data to text.'
complete -c irpipe -s t -l text2bin --description 'Convert text data to binary.'
complete -c irpipe -s s -l add-sync --description 'Add long initial sync on converted output.'
complete -c irpipe -s f -l filter --description 'Send data from stdin to stdout.'
complete -c irpipe -s r -l read --description 'Send data from kernel device to stdout.'
complete -c irpipe -o l--length --description 'Set kernel device signal length.'
complete -c irpipe -o F--features --description 'Set the features bitmask, as returned by the  LIRC_GET_FEATURES ioctl.'
complete -c irpipe -s h -l help --description 'Display usage summary.'
complete -c irpipe -s v -l version --description 'Display version.  KERNEL DRIVER.'

