# irrecord
# Autogenerated from man page /usr/share/man/man1/irrecord.1.gz
complete -c irrecord -s a -l analyse --description 'Analyse a raw_codes config file, trying to convert it to a regular configurat…'
complete -c irrecord -s u -l update --description 'Add new buttons to an existing config file.'
complete -c irrecord -s f -l force --description 'Force raw mode.  Use this if recording fails otherwise.'
complete -c irrecord -s n -l disable-namespace --description 'Disable namespace checks.'
complete -c irrecord -s l -l list-namespace --description 'List valid button names.'
complete -c irrecord -s H -l driver --description 'Use given driver.  -H help lists available drivers.'
complete -c irrecord -s d -l device --description 'Read from given device.'
complete -c irrecord -s U -l plugindir --description 'Load drivers from directory.  See DRIVER LOADING.'
complete -c irrecord -s k -l keep-root --description 'Don\'t drop root privileges after opening device.  See RUNNING AS ROOT.'
complete -c irrecord -s A -l driver-options --description 'Set one or more options for the driver.'
complete -c irrecord -s D -l loglevel --description 'Determine the amount of logging information.'
complete -c irrecord -s O -l options-file --description 'File containing default values for all options.'
complete -c irrecord -s h -l help --description 'Display this message.'
complete -c irrecord -s v -l version --description 'Display version.'

