# irsend
# Autogenerated from man page /usr/share/man/man1/irsend.1.gz
complete -c irsend -s h -l help --description 'Display usage summary.'
complete -c irsend -s v -l version --description 'Display version.'
complete -c irsend -s d -l device --description 'Use given lircd socket [/var/run/lirc/lircd].'
complete -c irsend -s a -l address --description 'Connect to lircd at this address.'
complete -c irsend -s '#' -l count --description 'Send command n times.'

