# irsimreceive
# Autogenerated from man page /usr/share/man/man1/irsimreceive.1.gz
complete -c irsimreceive -s U -l plugindir --description 'Load drivers from <dir>.'
complete -c irsimreceive -s v -l version --description 'Print version and exit.'
complete -c irsimreceive -s h -l help --description 'Print help message.'

