# irsimsend
# Autogenerated from man page /usr/share/man/man1/irsimsend.1.gz
complete -c irsimsend -s c -l count --description 'Repeat each sent signal <count> times.'
complete -c irsimsend -s U -l plugindir --description 'Load drivers from path, a \':\' separated search path similar to $PATH.'
complete -c irsimsend -s l -l listfile --description 'Send symbols listed in file instead of just the symbols in the config file.'
complete -c irsimsend -s k -l keysym --description 'Send a single key symbol defined in file.'
complete -c irsimsend -s s -l start-space --description 'Send an initial space before sending data.'
complete -c irsimsend -s v -l version --description 'Print version and exit.'
complete -c irsimsend -s h -l help --description 'Print help message.'

