# irtext2udp
# Autogenerated from man page /usr/share/man/man1/irtext2udp.1.gz
complete -c irtext2udp -s r -l resolution --description 'Udp packages are measured in ticks.'
complete -c irtext2udp -s v -l version --description 'Print version and exit.'
complete -c irtext2udp -s h -l help --description 'Print help message.'

