# irtestcase
# Autogenerated from man page /usr/share/man/man1/irtestcase.1.gz
complete -c irtestcase -s l -l lircrc --description 'Log also applications strings (as ircat(1)) using lircrc type config file.'
complete -c irtestcase -s p -l prog --description 'When using -l/--lircrc, the program name matching the PROG = entries in lircr…'
complete -c irtestcase -s t -l testdata --description 'Use data i file instead of "live" input from the remote.'
complete -c irtestcase -s v -l version --description 'Print version and exit.'
complete -c irtestcase -s h -l help --description 'Print help message.'

