# irw
# Autogenerated from man page /usr/share/man/man1/irw.1.gz
complete -c irw -s h -l help --description 'Display usage summary.'
complete -c irw -s v -l version --description 'Display version SIGNALS.'

