# itweb-settings
# Autogenerated from man page /usr/share/man/man1/itweb-settings.1.gz
complete -c itweb-settings -o check --description 'Checks that all the current settings have valid values.'
complete -c itweb-settings -o get --description 'Shows the value of the specified settings. (Expected one or more arguments).'
complete -c itweb-settings -o headless --description 'Disables download window, other UIs. (No argument expected).'
complete -c itweb-settings -o help --description 'Prints out information about supported command and basic usage.'
complete -c itweb-settings -o info --description 'Shows additional information about the named settings.'
complete -c itweb-settings -o list --description 'Shows a list of all the IcedTea-Web settings and their current values.'
complete -c itweb-settings -o reset --description 'Resets the specified settings to their original value.'
complete -c itweb-settings -o set --description 'Sets the settings to the new value specified, if it is an appropriate value.'
complete -c itweb-settings -o verbose --description 'Enable verbose output.'
complete -c itweb-settings -s 1 -s 1 --description '.'

