# jade
# Autogenerated from man page /usr/share/man/man1/jade.1.gz
complete -c jade -s d --description 'This specifies that dsssl_spec is the system identifier of the DSSSL specific…'
complete -c jade -s G --description 'Debug mode.'
complete -c jade -s c --description 'The filename arguments specify catalog files rather than the document entity.'
complete -c jade -s s --description 'Strict compliance mode.'
complete -c jade -s t --description 'output_type specifies the type of output as follows:.'
complete -c jade -s o --description 'Write output to output_file instead of the default.'
complete -c jade -s V --description 'This is equivalent to doing (define variable #t) except that this definition …'
complete -c jade -o wtype --description 'Control warnings and errors.  Multiple -w options are allowed.'

