# javah
# Autogenerated from man page /usr/share/man/man1/javah.1.gz
complete -c javah -s o --description 'Concatenates the resulting header or source files for all the classes listed …'
complete -c javah -s d --description 'Sets the directory where \\f3javah saves the header files or the stub files.'
complete -c javah -o stubs --description 'Causes \\f3javah to generate C declarations from the Java object file.'
complete -c javah -o verbose --description 'Indicates verbose output and causes \\f3javah to print a message to stdout con…'
complete -c javah -o help --description 'Print help message for \\f3javah usage.'
complete -c javah -o version --description 'Print out \\f3javah version information.'
complete -c javah -o jni --description 'Causes \\f3javah to create an output file containing JNI-style native method f…'
complete -c javah -o classpath --description 'Specifies the path \\f3javah uses to look up classes.'
complete -c javah -o bootclasspath --description 'Specifies path from which to load bootstrap classes.'
complete -c javah -o old --description 'Specifies that old JDK1. 0-style header files should be generated.'
complete -c javah -o force --description 'Specifies that output files should always be written.'

