# jcat-tool
# Autogenerated from man page /usr/share/man/man1/jcat-tool.1.gz
complete -c jcat-tool -s h -l help --description 'Show help options . SS "Application Options:".'
complete -c jcat-tool -l version --description 'Print the version number.'
complete -c jcat-tool -s v -l verbose --description 'Print verbose debug statements.'
complete -c jcat-tool -l basename --description 'Only consider the basename for the ID.'
complete -c jcat-tool -l public-key --description 'Location of public key used for verification.'
complete -c jcat-tool -l public-keys --description 'Location of public key directories used for verification.'
complete -c jcat-tool -l prefix --description 'Prefix for import and output files.'
complete -c jcat-tool -l kind --description 'Kind for blob, e. g.  `gpg`.'
complete -c jcat-tool -l appstream-id --description 'Appstream ID for blob, e. g.  `com. bbc`.'
complete -c jcat-tool -l keyring --description 'Keyring location, e. g.  `/var/lib/fwupd`.'

