# jcmd
# Autogenerated from man page /usr/share/man/man1/jcmd.1.gz
complete -c jcmd -s l --description 'Prints the list of running Java processes with their process IDs, their main …'
complete -c jcmd -s h --description 'Prints a help message.'

