# jjs-openjdk13
# Autogenerated from man page /usr/share/man/man1/jjs-openjdk13.1.gz
complete -c jjs-openjdk13 -o Dname --description 'Sets a system property to be passed to the script by assigning a value to a p…'
complete -c jjs-openjdk13 -l add-modules --description 'Specifies the root user Java modules.'
complete -c jjs-openjdk13 -o cp -o classpath --description 'Specifies the path to the supporting class files.'
complete -c jjs-openjdk13 -o doe -o dump-on-error --description 'Provides a full stack trace when an error occurs.'
complete -c jjs-openjdk13 -o fv -o fullversion --description 'Prints the full Nashorn version string.  The default parameter is false.'
complete -c jjs-openjdk13 -o fx --description 'Launches the script as a JavaFX application.  The default parameter is false.'
complete -c jjs-openjdk13 -s h -o help --description 'Prints the list of options and their descriptions.'
complete -c jjs-openjdk13 -l language --description 'Specifies the ECMAScript language version.  The default version is ES5.'
complete -c jjs-openjdk13 -l module-path --description 'Specifies where to find user Java modules.'
complete -c jjs-openjdk13 -o ot -o optimistic-types --description 'Enables or disables optimistic type assumptions with deoptimizing recompilati…'
complete -c jjs-openjdk13 -o scripting --description 'Enables a shell scripting features.  The default parameter is true.'
complete -c jjs-openjdk13 -o strict --description 'Enables a strict mode, which enforces stronger adherence to the standard (ECM…'
complete -c jjs-openjdk13 -s t -o timezone --description 'Sets the specified time zone for script execution.'
complete -c jjs-openjdk13 -s v --description 'Prints the Nashorn version string.  The default parameter is false.'

