# jmap
# Autogenerated from man page /usr/share/man/man1/jmap.1.gz
complete -c jmap -o 'dump:[live' --description 'Dumps the Java heap in hprof binary format to filename.'
complete -c jmap -o finalizerinfo --description 'Prints information on objects awaiting finalization. br.'
complete -c jmap -o heap --description 'Prints a heap summary.'
complete -c jmap -o histo --description 'Prints a histogram of the heap.'
complete -c jmap -o permstat --description 'Prints class loader wise statistics of permanent generation of Java heap.'
complete -c jmap -s F --description 'Force.  Use with jmap -dump or jmap -histo option if the pid does not respond.'
complete -c jmap -s h --description 'Prints a help message. br . br.'
complete -c jmap -o help --description 'Prints a help message. br . br.'

