# jps
# Autogenerated from man page /usr/share/man/man1/jps.1.gz
complete -c jps -s q --description 'Suppress the output of the class name, JAR file name, and arguments passed to…'
complete -c jps -s m --description 'Output the arguments passed to the main method.'
complete -c jps -s l --description 'Output the full package name for the application\'s main class or the full pat…'
complete -c jps -s v --description 'Output the arguments passed to the JVM.'
complete -c jps -s V --description 'Output the arguments passed to the JVM through the flags file (the .'
complete -c jps -o Joption --description 'Pass \\f2option to the \\f3java launcher called by \\f3jps.'

