# jrunscript-openjdk13
# Autogenerated from man page /usr/share/man/man1/jrunscript-openjdk13.1.gz
complete -c jrunscript-openjdk13 -o cp -o classpath --description 'Indicates where any class files are that the script needs to access.'
complete -c jrunscript-openjdk13 -o Dname --description 'Sets a Java system property.'
complete -c jrunscript-openjdk13 -o Jflag --description 'Passes flag directly to the Java Virtual Machine where the jrunscript command…'
complete -c jrunscript-openjdk13 -s l --description 'Uses the specified scripting language.  By default, JavaScript is used.'
complete -c jrunscript-openjdk13 -s e --description 'Evaluates the specified script.'
complete -c jrunscript-openjdk13 -o encoding --description 'Specifies the character encoding used to read script files.'
complete -c jrunscript-openjdk13 -s f --description 'Evaluates the specified script file (batch mode).'
complete -c jrunscript-openjdk13 -o help -s '?' --description 'Displays a help message and exits.'
complete -c jrunscript-openjdk13 -s q --description 'Lists all script engines available and exits.  ARGUMENTS.'

