# jstatd
# Autogenerated from man page /usr/share/man/man1/jstatd.1.gz
complete -c jstatd -o nr --description 'Do not attempt to create an internal RMI registry within the \\f2jstatd proces…'
complete -c jstatd -s p --description 'Port number where the RMI registry is expected to be found, or, if not found,…'
complete -c jstatd -s n --description 'Name to which the remote RMI object is bound in the RMI registry.'

