# kid3-qt
# Autogenerated from man page /usr/share/man/man1/kid3-qt.1.gz
complete -c kid3-qt -l portable --description 'Store configuration in file kid3. ini inside application directory.'
complete -c kid3-qt -l help --description 'Show help about options.'
complete -c kid3-qt -l author --description 'Show author information.'
complete -c kid3-qt -l version --description 'Show version information.'
complete -c kid3-qt -l license --description 'Show license information.'
complete -c kid3-qt -l desktopfile --description 'The base file name of the desktop entry for this application.'
complete -c kid3-qt -l dbus --description 'Activate the D-Bus interface.'
complete -c kid3-qt -s c --description 'Execute a command.'
complete -c kid3-qt -s h --description 'Show help about options and commands.'
complete -c kid3-qt -o /+ --description 'buttons.  Settings â Configure Kid3.'
complete -c kid3-qt -o DWITH_TAGLIB:BOOL -o DWITH_MP4V2:BOOL -o DWITH_ID3LIB:BOOL -o DWITH_CHROMAPRINT:BOOL -o DWITH_VORBIS:BOOL -o DWITH_FLAC:BOOL --description 'OFF.'
complete -c kid3-qt -o DWITH_APPS --description '.'
complete -c kid3-qt -o DQT_QMAKE_EXECUTABLE --description '.'

