# kjscmd5
# Autogenerated from man page /usr/share/man/man1/kjscmd5.1.gz
complete -c kjscmd5 -s e -l exec --description 'execute script in file without gui support.'
complete -c kjscmd5 -s i -l interactive --description 'start interactive kjs interpreter.'

