# lasem-render-0
# Autogenerated from man page /usr/share/man/man1/lasem-render-0.4.1.gz
complete -c lasem-render-0 -s h -l help --description 'Show summary of options.'
complete -c lasem-render-0 -s o -l output --description 'Output filename.'
complete -c lasem-render-0 -s f -l format --description 'Output format.'
complete -c lasem-render-0 -s p -l ppi --description 'Pixel per inch.'
complete -c lasem-render-0 -s z -l zoom --description 'Zoom.'
complete -c lasem-render-0 -s d -l debug --description 'Debug domains LICENSE lasem-render-0.'

