# librados-config
# Autogenerated from man page /usr/share/man/man8/librados-config.8.gz
complete -c librados-config -l version --description 'Display librados version.'
complete -c librados-config -l vernum --description 'Display the librados version code.'

