# link-parser
# Autogenerated from man page /usr/lib/jvm/default/man/man1/link-parser.1.gz
complete -c link-parser -l help --description 'Print usage and exit.'
complete -c link-parser -l version --description 'Print program version and configuration details, and exit.'
complete -c link-parser -l quiet --description 'Suppress the version messages on startup.'

