# lircrcd
# Autogenerated from man page /usr/share/man/man8/lircrcd.8.gz
complete -c lircrcd -s h -l help --description 'Display help message.'
complete -c lircrcd -s v -l version --description 'Display version.'
complete -c lircrcd -s p -l permission --description 'The --permission option gives the file permission of the Unix domain socket l…'
complete -c lircrcd -s o -l output --description 'With the --output option you can select the Unix domain socket, which lircrcd…'

