# lirc-lsplugins
# Autogenerated from man page /usr/share/man/man1/lirc-lsplugins.1.gz
complete -c lirc-lsplugins -s U -l plugindir --description 'Use <path> to search for plugins.'
complete -c lirc-lsplugins -s q -l quiet --description 'Don\'t write headers and trailing legend.'
complete -c lirc-lsplugins -s s -l summary --description 'Just write a summary over number of plugins, drivers and errors.'
complete -c lirc-lsplugins -s e -l errors --description 'Only list plugins which can\'t be loaded, or does not contain any drivers.'
complete -c lirc-lsplugins -s y -l yaml --description 'Make a YAML listing reflecting the drivers\' configuration hints such as the d…'
complete -c lirc-lsplugins -s l -l long --description 'Add info on driver features.'
complete -c lirc-lsplugins -s p -l default-path --description 'Print default search path and exit.'
complete -c lirc-lsplugins -s h -l help --description 'Display usage summary.'
complete -c lirc-lsplugins -s v -l version --description 'Display version info.'

