# lirc-config-tool
# Autogenerated from man page /usr/share/man/man1/lirc-config-tool.1.gz
complete -c lirc-config-tool -s s --description 'Scan lircd file for key symbols which are duplicated or not in namespace.'
complete -c lirc-config-tool -s u --description 'Update existing lircd file to use key symbols in namespace.'
complete -c lirc-config-tool -s l --description 'List available files to generate.'
complete -c lirc-config-tool -s d --description 'Dump file templates usable as stdin on stdout.'
complete -c lirc-config-tool -s o --description 'Output directory, defaults to ~/. config/lirc.'
complete -c lirc-config-tool -s c --description 'lircd(8) config file, defaults to /etc/lirc/lircd. conf.'
complete -c lirc-config-tool -s h --description 'Print help message.'

