# lirc-lsremotes
# Autogenerated from man page /usr/share/man/man1/lirc-lsremotes.1.gz
complete -c lirc-lsremotes -s d -l dump --description 'Dump the complete configuration data for listed configurations.'
complete -c lirc-lsremotes -s s -l silent --description 'Only print diagnostics.'
complete -c lirc-lsremotes -s v -l version --description 'Print version info.'
complete -c lirc-lsremotes -s h -l help --description 'Print help message.'

