# llvm-extract
# Autogenerated from man page /usr/share/man/man1/llvm-extract.1.gz
complete -c llvm-extract -s f --description 'Enable binary output on terminals.'
complete -c llvm-extract -l func --description 'Extract the function named function-name from the LLVM bitcode.'
complete -c llvm-extract -l rfunc --description 'Extract the function(s) matching function-regular-expr from the LLVM bitcode.'
complete -c llvm-extract -l glob --description 'Extract the global variable named global-name from the LLVM bitcode.'
complete -c llvm-extract -l rglob --description 'Extract the global variable(s) matching global-regular-expr from the LLVM bit…'
complete -c llvm-extract -o help --description 'Print a summary of command line options.'
complete -c llvm-extract -s o --description 'Specify the output filename.'
complete -c llvm-extract -s S --description 'Write output in LLVM intermediate language (instead of bitcode).  EXIT STATUS.'

