# llvm-strings
# Autogenerated from man page /usr/share/man/man1/llvm-strings.1.gz
complete -c llvm-strings -l all -s a --description 'Silently ignored.  Present for GNU strings compatibility.'
complete -c llvm-strings -l bytes -s n --description 'Set the minimum number of printable ASCII characters required for a sequence …'
complete -c llvm-strings -l help -s h --description 'Display a summary of command line options.'
complete -c llvm-strings -l help-list --description 'Display an uncategorized summary of command line options.'
complete -c llvm-strings -l print-file-name -s f --description 'Display the name of the containing file before each string.'
complete -c llvm-strings -l radix -s t --description 'Display the offset within the file of each string, before the string and usin…'
complete -c llvm-strings -l version --description 'Display the version of the llvm-strings executable.'

