# llvm-cxxfilt
# Autogenerated from man page /usr/share/man/man1/llvm-cxxfilt.1.gz
complete -c llvm-cxxfilt -l format -s s --description 'Mangling scheme to assume.'
complete -c llvm-cxxfilt -l help -s h --description 'Print a summary of command line options.'
complete -c llvm-cxxfilt -l help-list --description 'Print an uncategorized summary of command line options.'
complete -c llvm-cxxfilt -l strip-underscore -s _ --description 'Discard a single leading underscore, if present, from each input name before …'
complete -c llvm-cxxfilt -l types -s t --description 'Attempt to demangle names as type names as well as function names.'
complete -c llvm-cxxfilt -l version --description 'Display the version of the llvm-cxxfilt executable.'

