# llvm-ar
# Autogenerated from man page /usr/share/man/man1/llvm-ar.1.gz
complete -c llvm-ar -l format --description 'This option allows for default, gnu, darwin or bsd <type> to be selected.'
complete -c llvm-ar -s h -l help --description 'Print a summary of command-line options and their meanings.'
complete -c llvm-ar -s M --description 'This option allows for MRI scripts to be read through the standard input stre…'
complete -c llvm-ar -l version --description 'Display the version of the llvm-ar executable.'
complete -c llvm-ar -l plugin --description '.'

