# llvm-size
# Autogenerated from man page /usr/share/man/man1/llvm-size.1.gz
complete -c llvm-size -s A --description 'Equivalent to \\%--format with a value of sysv.'
complete -c llvm-size -l arch --description 'Architecture(s) from Mach-O universal binaries to display information for.'
complete -c llvm-size -s B --description 'Equivalent to \\%--format with a value of berkeley.'
complete -c llvm-size -l common --description 'Include ELF common symbol sizes in bss size for berkeley output format, or as…'
complete -c llvm-size -s d --description 'Equivalent to \\%--radix with a value of 10.'
complete -c llvm-size -s l --description 'Display verbose address and offset information for segments and sections in M…'
complete -c llvm-size -l format --description 'Set the output format to the <format> specified.'
complete -c llvm-size -l help -s h --description 'Display a summary of command line options.'
complete -c llvm-size -l help-list --description 'Display an uncategorized summary of command line options.'
complete -c llvm-size -s m --description 'Equivalent to \\%--format with a value of darwin.'
complete -c llvm-size -s o --description 'Equivalent to \\%--radix with a value of 8.'
complete -c llvm-size -l radix --description 'Display size information in the specified radix.'
complete -c llvm-size -l totals -s t --description 'Applies only to berkeley output format.'
complete -c llvm-size -l version --description 'Display the version of the llvm-size executable.'
complete -c llvm-size -s x --description 'Equivalent to \\%--radix with a value of 16.'

