# llvm-link
# Autogenerated from man page /usr/share/man/man1/llvm-link.1.gz
complete -c llvm-link -s f --description 'Enable binary output on terminals.'
complete -c llvm-link -s o --description 'Specify the output file name.'
complete -c llvm-link -s S --description 'Write output in LLVM intermediate language (instead of bitcode).'
complete -c llvm-link -s d --description 'If specified, llvm-link prints a human-readable version of the output bitcode…'
complete -c llvm-link -o help --description 'Print a summary of command line options.'
complete -c llvm-link -s v --description 'Verbose mode.   Print information about what llvm-link is doing.'

