# llvm-locstats
# Autogenerated from man page /usr/share/man/man1/llvm-locstats.1.gz
complete -c llvm-locstats -l only-variables --description 'calculate the location statistics only for local variables.'
complete -c llvm-locstats -l only-formal-parameters --description 'calculate the location statistics only for formal parameters.'
complete -c llvm-locstats -l ignore-debug-entry-values --description 'ignore the location statistics on locations containing the debug entry values…'
complete -c llvm-locstats -l draw-plot --description 'make histogram of location buckets generated (requires matplotlib).'

