# llvm-stress
# Autogenerated from man page /usr/share/man/man1/llvm-stress.1.gz
complete -c llvm-stress -s o --description 'Specify the output filename.'
complete -c llvm-stress -o size --description 'Specify the size of the generated . ll file.'
complete -c llvm-stress -o seed --description 'Specify the seed to be used for the randomly generated instructions.'

