# llvm-bcanalyzer
# Autogenerated from man page /usr/share/man/man1/llvm-bcanalyzer.1.gz
complete -c llvm-bcanalyzer -o nodetails --description 'Causes llvm-bcanalyzer to abbreviate its output by writing out only a module …'
complete -c llvm-bcanalyzer -o dump --description 'Causes llvm-bcanalyzer to dump the bitcode in a human readable format.'
complete -c llvm-bcanalyzer -o verify --description 'Causes llvm-bcanalyzer to verify the module produced by reading the bitcode.'
complete -c llvm-bcanalyzer -o help --description 'Print a summary of command line options.'

