# llvm-build
# Autogenerated from man page /usr/share/man/man1/llvm-build.1.gz
complete -c llvm-build -s h -l help --description 'Print the builtin program help.'
complete -c llvm-build -l source-root --description 'If given, load the project at the given source root path.'
complete -c llvm-build -l print-tree --description 'Print the component tree for the project.'
complete -c llvm-build -l write-library-table --description 'Write out the C++ fragment which defines the components, library names, and r…'
complete -c llvm-build -l write-llvmbuild --description 'Write out new LLVMBuild. txt files based on the loaded components.'
complete -c llvm-build -l write-cmake-fragment --description 'Write out the LLVMBuild in the form of a CMake fragment, so it can easily be …'
complete -c llvm-build -l write-make-fragment --description 'Write out the LLVMBuild in the form of a Makefile fragment, so it can easily …'
complete -c llvm-build -l llvmbuild-source-root --description 'If given, expect the LLVMBuild files for the project to be rooted at the give…'

