# llvm-lipo
# Autogenerated from man page /usr/share/man/man1/llvm-lipo.1.gz
complete -c llvm-lipo -o help -s h --description 'Display usage information and exit.'
complete -c llvm-lipo -o version --description 'Display the version of this program.'
complete -c llvm-lipo -o verify_arch --description 'Take a single input file and verify the specified architectures are present i…'
complete -c llvm-lipo -o archs --description 'Take a single input file and display the architectures present in the file.'
complete -c llvm-lipo -o info --description 'Take at least one input file and display the descriptions of each file.'
complete -c llvm-lipo -o thin --description 'Take a single universal binary input file and the thin flag followed by an ar…'
complete -c llvm-lipo -o create --description 'Take at least one input file and require the output flag to be specified.'
complete -c llvm-lipo -o replace --description 'Take a single universal binary input file and require the output flag to be s…'
complete -c llvm-lipo -o segalign --description 'Additional flag that can be specified with create and replace.'

