# lmms
# Autogenerated from man page /usr/share/man/man1/lmms.1.gz
complete -c lmms -l geometry --description 'Specify the prefered size and position of the main window.'
complete -c lmms -s c -l config --description 'Get the configuration from configfile instead of ~/. lmmsrc. xml (default).'
complete -c lmms -s h -l help --description 'Show usage information and exit.'
complete -c lmms -s v -l version --description 'Show version information and exit.'
complete -c lmms -s a -l float --description 'Use 32bit float bit depth.'
complete -c lmms -s b -l bitrate --description 'Specify output bitrate in KBit/s (for OGG encoding only), default is 160.'
complete -c lmms -s f -l format --description 'Specify format of render-output where format is either \'wav\', \'ogg\' or \'mp3\'.'
complete -c lmms -s i -l interpolation --description 'Specify interpolation method - possible values are linear, sincfastest (defau…'
complete -c lmms -s l -l loop --description 'Render the given file as a loop, i. e.'
complete -c lmms -s m -l mode --description 'Set the stereo mode used for the MP3 export.'
complete -c lmms -s o -l output --description 'Render into path.'
complete -c lmms -s p -l profile --description 'Dump profiling information to file out.'
complete -c lmms -s s -l samplerate --description 'Specify output samplerate in Hz - range is 44100 (default) to 192000.'
complete -c lmms -s x -l oversampling --description 'Specify oversampling, possible values: 1, 2 (default), 4, 8.'

