# lqtplay
# Autogenerated from man page /usr/share/man/man1/lqtplay.1.gz
complete -c lqtplay -o noxv --description 'Don\'t use the Xvideo extension for accelerated video playback (YUV->RGB color…'
complete -c lqtplay -o nogl --description 'Don\'t use OpenGL (via GLX extension) for video scaling.'
complete -c lqtplay -o noalsa --description 'Don\'t use Alsa for audio output.'

