# malcontent-client
# Autogenerated from man page /usr/share/man/man8/malcontent-client.8.gz
complete -c malcontent-client -s q -l quiet --description 'Only output error messages, and no informational messages, as the operation p…'
complete -c malcontent-client -s n -l no-interactive --description 'Do not allow interactive authorization with polkit.'

