# meld
# Autogenerated from man page /usr/share/man/man1/meld.1.gz
complete -c meld -l auto-compare -s a --description 'br Automatically compare all differing files on startup.'
complete -c meld -l auto-merge --description 'br Automatically merge files.'
complete -c meld -l comparison-file --description 'br Load a saved comparison from a Meld comparison file.'
complete -c meld -l diff --description 'br Create a diff tab for the given files or directories.'
complete -c meld -l help -s h --description 'br Print application help and usage.'
complete -c meld -l label -s L --description 'br Set application window title to <label>.'
complete -c meld -l newtab -s n --description 'br Open the comparison as a new tab in an already-running instance.'
complete -c meld -l output -s o --description 'br Sets the save path for the middle buffer in a three-pane merge view.'
complete -c meld -l unified -s u --description 'br Ignored for compatibility.'
complete -c meld -l version --description '.'

