# midicat
# Autogenerated from man page /usr/share/man/man1/midicat.1.gz
complete -c midicat -s d --description 'Dump transferred data in hex on stderr.'
complete -c midicat -s i --description 'Read MIDI data from this file instead of receiving it from the MIDI port.'
complete -c midicat -s o --description 'Write MIDI data to this file instead of sending it to the MIDI port.'
complete -c midicat -s q --description 'Use this sndio 7 MIDI port for input/output.'

