# miredo-server
# Autogenerated from man page /usr/share/man/man8/miredo-server.8.gz
complete -c miredo-server -s c -l config --description 'Specify an alternate configuration file for Miredo instead of the .'
complete -c miredo-server -s f -l foreground --description 'Do not detach from the console.  Run the program in the foreground.'
complete -c miredo-server -s h -l help --description 'Display some help and exit.'
complete -c miredo-server -s u -l user --description 'Override the user that the program will run as.'
complete -c miredo-server -s V -l version --description 'Display program version and license and exit.'

