# modem_run
# Autogenerated from man page /usr/share/man/man8/modem_run.8.gz
complete -c modem_run -s f --description 'Specifies the file containing the firmware code of the modem.'
complete -c modem_run -s a --description 'Specifies the file containing the boot code of the modem.'
complete -c modem_run -s b --description 'Enables the use of the modem\'s "software buffering" mode.'
complete -c modem_run -s d --description 'Defines which USB device should be used as the SpeedTouch USB modem.'
complete -c modem_run -s i --description 'Defines the time between each device state polling.  The default is 10s.'
complete -c modem_run -s k --description 'Enables "speedtch" Linux kernel module coupling.'
complete -c modem_run -s n --description 'Number of firmware upload tries before failure is reported.'
complete -c modem_run -s r --description 'Forces a specific modem revision.  Valid values range from 0 to 4.'
complete -c modem_run -s s --description 'Skips the first 512 bytes read (if you have a bulk read error 512 bytes on st…'
complete -c modem_run -s t --description 'Sets the sychronization timeout in seconds.  The default is 120s.'
complete -c modem_run -s v --description 'Verbosity level     - 0 Error messages     - 1 level 0 + State messages     -…'
complete -c modem_run -l help --description 'display this help and exit DEPRECATED.'
complete -c modem_run -s m --description 'This option used to be specified to make modem_run monitor the state line in …'

