# mode2
# Autogenerated from man page /usr/share/man/man1/mode2.1.gz
complete -c mode2 -s d -l device --description 'Read from given device.'
complete -c mode2 -s H -l driver --description 'Use given driver.'
complete -c mode2 -s m -l mode --description 'Write pulse/space data as raw config files.  Does not affect LIRCCODE drivers.'
complete -c mode2 -s s -l scope --description 'Enable \'scope like display with time us per char.'
complete -c mode2 -s k -l keep-root --description 'Don\'t drop root privileges after opening device.  See RUNNING AS ROOT.'
complete -c mode2 -s l -l list-devices --description 'List all available devices for given driver.'
complete -c mode2 -s g -l gap --description 'Treat spaces longer than time as the gap.  Time is in microseconds.'
complete -c mode2 -s r -l raw --description 'Access device directly.'
complete -c mode2 -s A -l driver-options --description 'Set driver-specific option named key to given value.'
complete -c mode2 -s U -l plugindir --description 'Load drivers from directory.  See DRIVER LOADING.'
complete -c mode2 -s O -l options-file --description 'File containing default values for all options.'
complete -c mode2 -s D -l loglevel --description 'Determine the amount of logging information.'
complete -c mode2 -s h -l help --description 'Display usage summary.'
complete -c mode2 -s v -l version --description 'Display version.'

