# monmaptool
# Autogenerated from man page /usr/share/man/man8/monmaptool.8.gz
complete -c monmaptool -l print --description 'will print a plaintext dump of the map, after any modifications are made.'
complete -c monmaptool -l clobber --description 'will allow monmaptool to overwrite mapfilename if changes are made.'
complete -c monmaptool -l create --description 'will create a new monitor map with a new UUID (and with it, a new, empty Ceph…'
complete -c monmaptool -l generate --description 'generate a new monmap based on the values on the command line or specified in…'
complete -c monmaptool -l filter-initial-members --description 'filter the initial monmap by applying the mon initial members setting.'
complete -c monmaptool -l add --description 'will add a monitor with the specified ip:port to the map.'
complete -c monmaptool -l rm --description 'will remove the monitor with the specified ip:port from the map.'
complete -c monmaptool -l fsid --description 'will set the fsid to the given uuid.'
complete -c monmaptool -l monmap --description '2.  3.'
complete -c monmaptool -l mon-host --description '3.  3 [mon. foo] sections containing mon addr settings in the config.'

