# name2addr
# Autogenerated from man page /usr/share/man/man1/name2addr.1.gz
complete -c name2addr -s 4 -l ipv4 --description 'Only try to perform IPv4 lookups.'
complete -c name2addr -s 6 -l ipv6 --description 'Only try to perform IPv6 lookups.'
complete -c name2addr -s c -l config --description 'Only lookup and print results for address families that match locally configu…'
complete -c name2addr -s h -l help --description 'Display some help and exit.'
complete -c name2addr -s m -l multiple --description 'Normally, if a name yields multiple results, only the first one is printed.'
complete -c name2addr -s n -l numeric --description 'Prevent forward hostname lookup.'
complete -c name2addr -s r -l reverse --description 'Perform a reverse DNS lookup . RB "(enabled implicitly with " "addr2name" ").'
complete -c name2addr -l version --description 'Display program version and license and exit.'

