# native2ascii
# Autogenerated from man page /usr/share/man/man1/native2ascii.1.gz
complete -c native2ascii -o reverse --description 'Perform the reverse operation: Convert a file encoded in ISO-8859-1 with Unic…'
complete -c native2ascii -o encoding --description 'Specifies the name of the character encoding to be used by the conversion pro…'

