# ndctl-update-firmware
# Autogenerated from man page /usr/share/man/man1/ndctl-update-firmware.1.gz
complete -c ndctl-update-firmware -s b -l bus --description '.'
complete -c ndctl-update-firmware -s f -l firmware --description '.'
complete -c ndctl-update-firmware -s v -l verbose --description '.'

