# ndisc6
# Autogenerated from man page /usr/share/man/man8/ndisc6.8.gz
complete -c ndisc6 -s 1 -l single --description 'Exit as soon as the first advertisement is received (default).'
complete -c ndisc6 -s h -l help --description 'Display some help and exit.'
complete -c ndisc6 -s m -l multiple --description 'Wait for possible duplicate advertisements and print all of them.'
complete -c ndisc6 -s n -l numeric --description 'If the first parameter is not a valid IPv6 address, do not try to resolve it …'
complete -c ndisc6 -s q -l quiet --description 'Only display link-layer address.  Display nothing in case of failure.'
complete -c ndisc6 -s r -l retry --description 'Send ICMPv6 Neighbor Discovery that many times until a reply is received, or …'
complete -c ndisc6 -s s -l source --description 'Specify the IPv6 address to be used as the source for the neighbor solicitati…'
complete -c ndisc6 -s V -l version --description 'Display program version and license and exit.'
complete -c ndisc6 -s v -l verbose --description 'Display verbose information.  That is the default.'
complete -c ndisc6 -s w -l wait --description 'Wait  wait_ms  milliseconds for a response before retrying.'

