# ocamlmktop
# Autogenerated from man page /usr/lib/jvm/default/man/man1/ocamlmktop.1.gz
complete -c ocamlmktop -s v --description 'Print the version string of the compiler and exit.'
complete -c ocamlmktop -o vnum -o version --description 'Print the version number of the compiler in short form and exit.'
complete -c ocamlmktop -o cclib-l --description 'Pass the  -l libname option to the C linker when linking in ``custom runtime\'…'
complete -c ocamlmktop -o ccopt --description 'Pass the given option to the C compiler and linker, when linking in ``custom …'
complete -c ocamlmktop -o custom --description 'Link in ``custom runtime\'\' mode.'
complete -c ocamlmktop -s I --description 'Add the given directory to the list of directories searched for compiled inte…'
complete -c ocamlmktop -o cclib -s l --description 'Pass the.'
complete -c ocamlmktop -s o --description 'Specify the name of the toplevel file produced by the linker.'

