# ocamldebug
# Autogenerated from man page /usr/lib/jvm/default/man/man1/ocamldebug.1.gz
complete -c ocamldebug -s c --description 'Set the maximum number of simultaneously live checkpoints to R count .'
complete -c ocamldebug -o cd --description 'Run the debugger program from the working directory R dir , instead of the cu…'
complete -c ocamldebug -o emacs --description 'Tell the debugger it is executed under Emacs.'
complete -c ocamldebug -s I --description 'Add  directory to the list of directories searched for source files and compi…'
complete -c ocamldebug -o machine-readable --description 'Print information in a format more suitable for machines instead of human ope…'
complete -c ocamldebug -s s --description 'Use  socket for communicating with the debugged program.'
complete -c ocamldebug -o version --description 'Print version string and exit.'
complete -c ocamldebug -o vnum --description 'Print short version number and exit.'
complete -c ocamldebug -s g --description 'option: all . cmo and .'
complete -c ocamldebug -o help -l help --description 'Display a short usage summary and exit.'

