# ocamlyacc
# Autogenerated from man page /usr/lib/jvm/default/man/man1/ocamlyacc.1.gz
complete -c ocamlyacc -s b --description 'Name the output files R prefix . ml, R prefix . mli, R prefix .'
complete -c ocamlyacc -s q --description 'This option has no effect.'
complete -c ocamlyacc -l strict --description 'Reject grammars with conflicts.'
complete -c ocamlyacc -s v --description 'Generate a description of the parsing tables and a report on conflicts result…'
complete -c ocamlyacc -o version --description 'Print version string and exit.'
complete -c ocamlyacc -o vnum --description 'Print short version number and exit.'

