# ocamlcp
# Autogenerated from man page /usr/lib/jvm/default/man/man1/ocamlcp.1.gz
complete -c ocamlcp -o pp --description 'option is not supported.'
complete -c ocamlcp -s P --description 'option.  The letters indicate which parts of the program should be profiled:.'
complete -c ocamlcp -s p --description 'with the same argument and meaning as.'

