# opt
# Autogenerated from man page /usr/share/man/man1/opt.1.gz
complete -c opt -s f --description 'Enable binary output on terminals.'
complete -c opt -o help --description 'Print a summary of command line options.'
complete -c opt -s o --description 'Specify the output filename.'
complete -c opt -s S --description 'Write output in LLVM intermediate language (instead of bitcode).'
complete -c opt -o disable-inlining --description 'This option simply removes the inlining pass from the standard list.'
complete -c opt -o disable-opt --description 'This option is only meaningful when -std-link-opts is given.'
complete -c opt -o strip-debug --description 'This option causes opt to strip debug information from the module before appl…'
complete -c opt -o verify-each --description 'This option causes opt to add a verify pass after every pass otherwise specif…'
complete -c opt -o stats --description 'Print statistics.'
complete -c opt -o time-passes --description 'Record the amount of time needed for each pass and print it to standard error.'
complete -c opt -o debug --description 'If this is a debug build, this option will enable debug printouts from passes…'
complete -c opt -o load --description 'Load the dynamic object plugin.'
complete -c opt -s p --description 'Print module after each transformation.'

