# osinfo-install-script
# Autogenerated from man page /usr/share/man/man1/osinfo-install-script.1.gz
complete -c osinfo-install-script -l profile --description 'Choose the installation script profile.'
complete -c osinfo-install-script -l installation-source --description 'Set the installation source to be used with the installation script.'
complete -c osinfo-install-script -l config --description 'Set the configuration parameter \\f(CW\\*(C`key\\*(C\' to \\f(CW\\*(C`value\\*(C\'.'

