# pfd
# Autogenerated from man page /usr/share/man/man1/pfd.1.gz
complete -c pfd -s x -l xft --description 'Print font name in xft format.  This is default.'
complete -c pfd -s p -l pango --description 'Print font name in pango format.'
complete -c pfd -s h -l help --description 'Print help.'
complete -c pfd -s v -l version --description 'Print current version.'

