# pffexport
# Autogenerated from man page /usr/share/man/man1/pffexport.1.gz
complete -c pffexport -s c --description 'specify the codepage of ASCII strings, options: ascii, windows-874, windows-9…'
complete -c pffexport -s d --description 'dumps the item values in a separate file: ItemValues. txt.'
complete -c pffexport -s f --description 'specify the preferred output format, options: all, html, rtf, text (default).'
complete -c pffexport -s h --description 'shows this help.'
complete -c pffexport -s l --description 'specify the file in which to log information about the exported items.'
complete -c pffexport -s m --description 'export mode, option: all, debug, items (default), recovered.'
complete -c pffexport -s q --description 'quiet shows minimal status information.'
complete -c pffexport -s t --description 'specify the basename of the target directory to export to (default is the sou…'
complete -c pffexport -s v --description 'verbose output to stderr.'
complete -c pffexport -s V --description 'print version El ENVIRONMENT None FILES None EXAMPLES -literal # pffexport fi…'

