# pffinfo
# Autogenerated from man page /usr/share/man/man1/pffinfo.1.gz
complete -c pffinfo -s a --description 'shows allocation information.'
complete -c pffinfo -s c --description 'specify the codepage of ASCII strings, options: ascii, windows-874, windows-9…'
complete -c pffinfo -s h --description 'shows this help.'
complete -c pffinfo -s v --description 'verbose output to stderr.'
complete -c pffinfo -s V --description 'print version El ENVIRONMENT None FILES None EXAMPLES -literal # pffinfo -a f…'

