# pixz
# Autogenerated from man page /usr/share/man/man1/pixz.1.gz
complete -c pixz -s d --description 'Decompress, instead of compress.'
complete -c pixz -s t --description 'Force non-tarball mode.'
complete -c pixz -s l --description 'List the archive contents.  In tarball mode, lists the files in the tarball.'
complete -c pixz -s x --description 'Extract certain members from an archive, quickly.'
complete -c pixz -s i --description 'Use INPUT as the input.'
complete -c pixz -s o --description 'Use OUTPUT as the output.'
complete -c pixz -s '#' --description 'Set compression level, from -0 (lowest compression, fastest) to -9 (highest c…'
complete -c pixz -s e --description 'Use "extreme" compression, which is much slower and only yields a marginal de…'
complete -c pixz -s p --description 'Set the number of CPU cores to use.'
complete -c pixz -s f --description 'Set the size of each compression block, relative to the LZMA dictionary size …'
complete -c pixz -s q --description 'Set the number of blocks to allocate for the compression queue (default is 1.'
complete -c pixz -s h --description 'Show pixz\\(cqs online help.'

