# plasmaengineexplorer
# Autogenerated from man page /usr/share/man/man1/plasmaengineexplorer.1.gz
complete -c plasmaengineexplorer -s v -l version --description 'Displays version information.'
complete -c plasmaengineexplorer -s h -l help --description 'Displays this help.'
complete -c plasmaengineexplorer -l list --description 'Displays a list of known engines and their descriptions.'
complete -c plasmaengineexplorer -l height --description 'Sets the height of the window, in pixels.'
complete -c plasmaengineexplorer -l width --description 'Sets the width of the window, in pixels.'
complete -c plasmaengineexplorer -s x --description 'Sets the x (horizontal) co-ordinate of the top left corner of the window, in …'
complete -c plasmaengineexplorer -s y --description 'Sets the y (vertical) co-ordinate of the top left corner of the window, in pi…'
complete -c plasmaengineexplorer -l engine --description 'Start plasmaengineexplorer with the given data engine selected.'
complete -c plasmaengineexplorer -l source --description 'Only valid in conjunction with --engine.'
complete -c plasmaengineexplorer -l interval --description 'Sets the default update interval for requested sources to time milliseconds.'
complete -c plasmaengineexplorer -l app --description 'Only show engines associated with the parent application; maps to the X-KDE-P…'

