# plasmoidviewer
# Autogenerated from man page /usr/share/man/man1/plasmoidviewer.1.gz
complete -c plasmoidviewer -s v -l version --description 'Displays version information.'
complete -c plasmoidviewer -s c -l containment --description 'The name of the containment plugin.'
complete -c plasmoidviewer -s a -l applet --description 'The name of the applet plugin.'
complete -c plasmoidviewer -s f -l formfactor --description 'The formfactor to use (horizontal, vertical, mediacenter, planar or applicati…'
complete -c plasmoidviewer -s l -l location --description 'The location constraint to start the Containment with (floating, desktop, ful…'
complete -c plasmoidviewer -s x -l xPosition --description 'Set the x position of the plasmoidviewer on the Plasma desktop.'
complete -c plasmoidviewer -s y -l yPosition --description 'Set the y position of the plasmoidviewer on the Plasma desktop.'
complete -c plasmoidviewer -s s -l size --description 'Set the window size of the plasmoidview.'
complete -c plasmoidviewer -s p -l pixmapcache --description 'The size in KB to set the pixmap cache to.'
complete -c plasmoidviewer -s t -l theme --description 'The name of the theme which the shell will use.'
complete -c plasmoidviewer -s h -l help --description 'Displays this help.'

