# podofoencrypt
# Autogenerated from man page /usr/share/man/man1/podofoencrypt.1.gz
complete -c podofoencrypt -l help --description '.'
complete -c podofoencrypt -l rc4v1 --description '.'
complete -c podofoencrypt -l rc4v2 --description '.'
complete -c podofoencrypt -l aes --description '.'
complete -c podofoencrypt -s u --description '.'
complete -c podofoencrypt -s o --description '.'
complete -c podofoencrypt -l print --description 'Allow printing the document.'
complete -c podofoencrypt -l edit --description 'Allow modification of the document besides annotations, form fields or changi…'
complete -c podofoencrypt -l copy --description 'Allow extraction of text and graphics.'
complete -c podofoencrypt -l editnotes --description 'Add or modify text annotations or form fields (if ePdfPermissions_Edit is set…'
complete -c podofoencrypt -l fillandsign --description 'Fill in existing form or signature fields.'
complete -c podofoencrypt -l accessible --description 'Extract text and graphics to support user with disabillities.'
complete -c podofoencrypt -l assemble --description 'Assemble the document: insert, create, rotate delete pages or add bookmarks.'
complete -c podofoencrypt -l highprint --description 'Print a high resolution version of the document.'

