# podofotxt2pdf
# Autogenerated from man page /usr/share/man/man1/podofotxt2pdf.1.gz
complete -c podofotxt2pdf -o fontname --description 'Use the font <name>.'
complete -c podofotxt2pdf -o utf8 --description 'specifies that the input text is UTF8 encoded instead of Windows ANSI encodin…'

