# podofopages
# Autogenerated from man page /usr/share/man/man1/podofopages.1.gz
complete -c podofopages -l delete --description 'Deletes the page NUMBER (number is 0-based).'
complete -c podofopages -l move --description 'Moves a page FROM TO in the document (FROM and TO are 0-based).'

