# policyeditor
# Autogenerated from man page /usr/share/man/man1/policyeditor.1.gz
complete -c policyeditor -o codebase --description 'Specifies an applet codebase URL.'
complete -c policyeditor -o defaultfile --description 'Specifies that the default user-level policy file should be opened.'
complete -c policyeditor -o file --description 'Specifies a policy file path to open.'
complete -c policyeditor -o help --description 'Prints out information about supported command and basic usage.'
complete -c policyeditor -o principals --description 'Specifies class name/principal name pairs (space-separated) for the policy en…'
complete -c policyeditor -o signedby --description 'Specifies a certificate alias for a certificate stored in the keystore.'
complete -c policyeditor -o verbose --description 'Enable verbose output. (No argument expected).'

