# powerline-daemon
# Autogenerated from man page /usr/share/man/man1/powerline-daemon.1.gz
complete -c powerline-daemon -l quiet -s q --description 'Without other options: do not complain about already running powerline-daemon…'
complete -c powerline-daemon -l socket -s s --description 'Specify socket which will be used for connecting to daemon.'
complete -c powerline-daemon -l kill -s k --description 'Kill an already running instance.'
complete -c powerline-daemon -l foreground -s f --description 'Run in the foreground (donât daemonize).'
complete -c powerline-daemon -l replace -s r --description 'Replace an already running instance.'
complete -c powerline-daemon -s h -l help --description 'Display help and exit.'

