# powerline
# Autogenerated from man page /usr/share/man/man1/powerline.1.gz
complete -c powerline -s r -l renderer-module --description 'Renderer module.  Usually something like . bash or .'
complete -c powerline -s w -l width --description 'Maximum prompt with.  Triggers truncation of some segments.'
complete -c powerline -l last-exit-code --description 'Last exit code.'
complete -c powerline -l last-pipe-status --description 'Like above, but is supposed to contain space-separated array of statuses, rep…'
complete -c powerline -l jobnum --description 'Number of jobs.'
complete -c powerline -s c -l config-override --description 'Configuration overrides for config. json.'
complete -c powerline -s t -l theme-override --description 'Like above, but theme-specific.'
complete -c powerline -s R -l renderer-arg --description 'Like above, but provides argument for renderer.'
complete -c powerline -s p -l config-path --description 'Path to configuration directory.'
complete -c powerline -l socket --description 'Socket address to use in daemon clients.'
complete -c powerline -s h -l help --description 'Display help and exit.'

