# powerline-config
# Autogenerated from man page /usr/share/man/man1/powerline-config.1.gz
complete -c powerline-config -s p -l config-path --description 'Path to configuration directory.'
complete -c powerline-config -s h -l help --description 'Display help and exit. UNINDENT .'
complete -c powerline-config -s s -l source --description 'When using setup: always use configuration file sourcing.'
complete -c powerline-config -s n -l no-source --description 'When using setup: in place of sourcing directly execute configuration files.'
complete -c powerline-config -l shell --description 'Shell for which query is run.'

