# powerline-lint
# Autogenerated from man page /usr/share/man/man1/powerline-lint.1.gz
complete -c powerline-lint -s p -l config-path --description 'Paths where configuration should be checked, in order.'
complete -c powerline-lint -s d -l debug --description 'Display additional information.'
complete -c powerline-lint -s h -l help --description 'Display help and exit.'

