# pppoa2
# Autogenerated from man page /usr/share/man/man8/pppoa2.8.gz
complete -c pppoa2 -s b --description 'Bridging 1483 mode (PPPoE support).'
complete -c pppoa2 -s d --description 'Defines which USB device should be used as the SpeedTouch USB modem.'
complete -c pppoa2 -s e --description 'Use an alternate endpoint interface.'
complete -c pppoa2 -s f --description 'Defines the pppoa2 log file name (by default /var/log/pppoa2. log).'
complete -c pppoa2 -s v --description 'Verbosity level     - 0 Main messages + Error messages     - 1 level 0 + Stat…'
complete -c pppoa2 -o vpi --description 'Defines vpi value.'
complete -c pppoa2 -o vci --description 'Defines vci value.'
complete -c pppoa2 -l help --description 'display this help and exit.'

