# pppoa3
# Autogenerated from man page /usr/share/man/man8/pppoa3.8.gz
complete -c pppoa3 -l async -s a --description 'Force Async mode for ppp communication.'
complete -c pppoa3 -l bridging -s b --description 'Bridging 1483 mode (PPPoE support).'
complete -c pppoa3 -l clean -s c --description 'Clean previous instance of pppoa3 according to modem ID.'
complete -c pppoa3 -l device -s d --description 'Defines which USB device should be used as the SpeedTouch USB modem.'
complete -c pppoa3 -l alt-ep -s e --description 'Use an alternate endpoint interface.'
complete -c pppoa3 -l filename -s f --description 'Defines the log filename to use (Default /var/log/pppoa3-ModemID. log)\\n.'
complete -c pppoa3 -l modem -s m --description 'Defines a modem ID so you can use more than one modem on the same machine run…'
complete -c pppoa3 -l pipe -s p --description 'Enables named pipe control thread (See the -ph option for more details).'
complete -c pppoa3 -l schedule -s s --description 'Defines the schedule policy used for the io threads     0 - SCHED_OTHER (Non …'
complete -c pppoa3 -l verbose -s v --description 'Verbosity level     - 0 Main messages + Error messages     - 1 level 0 + Stat…'
complete -c pppoa3 -l pipehelp -o ph --description 'Prints an helpfull control pipe command list (See next section).'
complete -c pppoa3 -o vpi --description 'Defines vpi value.'
complete -c pppoa3 -o vci --description 'Defines vci value.'
complete -c pppoa3 -l help -s h --description 'Prints a help message.'

