# psensor
# Autogenerated from man page /usr/share/man/man1/psensor.1.gz
complete -c psensor -s h -l help --description 'display this help and exit.'
complete -c psensor -s v -l version --description 'display version information and exit.'
complete -c psensor -s u -l url --description 'the URL of the psensor-server, example: http://hostname:3131.'
complete -c psensor -s n -l new-instance --description 'force the creation of a new Psensor application.'
complete -c psensor -s d -l debug --description 'set the debug level, integer between 0 and 3 REPORTING BUGS Report bugs to: j…'

