# psensor-server
# Autogenerated from man page /usr/share/man/man1/psensor-server.1.gz
complete -c psensor-server -s h -l help --description 'display this help and exit.'
complete -c psensor-server -s v -l version --description 'display version information and exit.'
complete -c psensor-server -s p -l port --description 'webserver port.'
complete -c psensor-server -s w -l wdir --description 'directory containing webserver pages.'
complete -c psensor-server -s d -l debug --description 'set the debug level, integer between 0 and 3.'
complete -c psensor-server -s l -l log-file --description 'set the log file to PATH.'
complete -c psensor-server -l sensor-log-file --description '.'
complete -c psensor-server -l sensor-log-interval --description 'SENSOR LOG FILE.'

