# psiconv-config
# Autogenerated from man page /usr/lib/jvm/default/man/man1/psiconv-config.1.gz
complete -c psiconv-config -l version --description 'Print the currently installed version of psiconv on the standard output.'
complete -c psiconv-config -l libs --description 'Print the linker flags that are necessary to link a psiconv program.'
complete -c psiconv-config -l cflags --description 'Print the compiler flags that are necessary to compile a psiconv program.'
complete -c psiconv-config -l prefix --description 'If specified, use PREFIX instead of the installation prefix that psiconv was …'
complete -c psiconv-config -l exec-prefix --description 'If specified, use PREFIX instead of the installation exec prefix that psiconv…'

