# psiconv
# Autogenerated from man page /usr/lib/jvm/default/man/man1/psiconv.1.gz
complete -c psiconv -s c -l configfile --description 'Read an additional configuration file after the default ones.  See psiconv.'
complete -c psiconv -s e -l encoding --description 'Output encoding.'
complete -c psiconv -s h -l help --description 'Output a small usage guide as well as the supported output formats on stdout …'
complete -c psiconv -s n -l noise --description 'The amount of noise generated on stderr.'
complete -c psiconv -s o -l outputfile --description 'File to write output to, instead of stdout.'
complete -c psiconv -s T -l type --description 'The file format to output.'
complete -c psiconv -s V -l version --description 'Output the current version of psiconv on stdout and exit successfully.'

