# qtractor
# Autogenerated from man page /usr/share/man/man1/qtractor.1.gz
complete -c qtractor -s s -l session-id --description 'Set session identification (uuid).'
complete -c qtractor -s '?' -l help --description 'Show help about command line options.'
complete -c qtractor -s v -l version --description 'Show version information FILES Configuration settings are stored in ~/.'

