# radosgw
# Autogenerated from man page /usr/share/man/man8/radosgw.8.gz
complete -c radosgw -s c -l conf --description 'Use ceph. conf configuration file instead of the default /etc/ceph/ceph.'
complete -c radosgw -s m --description 'Connect to specified monitor (instead of looking through ceph. conf).'
complete -c radosgw -s i -l id --description 'Set the ID portion of name for radosgw.'
complete -c radosgw -s n -l name --description 'Set the rados user name for the gateway (eg.  client. radosgw. gateway).'
complete -c radosgw -l cluster --description 'Set the cluster name (default: ceph).'
complete -c radosgw -s d --description 'Run in foreground, log to stderr.'
complete -c radosgw -s f --description 'Run in foreground, log to usual location.'
complete -c radosgw -l rgw-socket-path --description 'Specify a unix domain socket path.'
complete -c radosgw -l rgw-region --description 'The region where radosgw runs.'
complete -c radosgw -l rgw-zone --description 'The zone where radosgw runs.'

