# rados
# Autogenerated from man page /usr/share/man/man8/rados.8.gz
complete -c rados -s p -l pool --description 'Interact with the given pool.  Required by most commands.'
complete -c rados -l pgid --description 'As an alternative to --pool, --pgid also allow users to specify the PG id to …'
complete -c rados -s N -l namespace --description 'Specify the rados namespace to use for the object.'
complete -c rados -s s -l snap --description 'Read from the given pool snapshot.'
complete -c rados -s i --description 'will specify an input file to be passed along as a payload with the command t…'
complete -c rados -s o --description 'will write any payload returned by the monitor cluster with its reply to outf…'
complete -c rados -s c -l conf --description 'Use ceph. conf configuration file instead of the default /etc/ceph/ceph.'
complete -c rados -s m --description 'Connect to specified monitor (instead of looking through ceph. conf).'
complete -c rados -s b --description 'Set the block size for put/get/append ops and for write benchmarking.'
complete -c rados -l striper --description 'Uses the striping API of rados rather than the default one.'

