# rbd-mirror
# Autogenerated from man page /usr/share/man/man8/rbd-mirror.8.gz
complete -c rbd-mirror -s c -l conf --description 'Use ceph. conf configuration file instead of the default /etc/ceph/ceph.'
complete -c rbd-mirror -s m --description 'Connect to specified monitor (instead of looking through ceph. conf).'
complete -c rbd-mirror -s i -l id --description 'Set the ID portion of name for rbd-mirror.'
complete -c rbd-mirror -s n -l name --description 'Set the rados user name for the gateway (eg.  clientd-mirror).'
complete -c rbd-mirror -l cluster --description 'Set the cluster name (default: ceph).'
complete -c rbd-mirror -s d --description 'Run in foreground, log to stderr.'
complete -c rbd-mirror -s f --description 'Run in foreground, log to usual location.'

