# rbd-nbd
# Autogenerated from man page /usr/share/man/man8/rbd-nbd.8.gz
complete -c rbd-nbd -s c --description 'Use ceph. conf configuration file instead of the default /etc/ceph/ceph.'
complete -c rbd-nbd -l read-only --description 'Map read-only.'
complete -c rbd-nbd -l nbds_max --description 'Override the parameter of NBD kernel module when modprobe, used to limit the …'
complete -c rbd-nbd -l max_part --description 'Override for module param nbds_max.'
complete -c rbd-nbd -l exclusive --description 'Forbid writes by other clients.'
complete -c rbd-nbd -l timeout --description 'Override device timeout.'

