# rbd-replay-prep
# Autogenerated from man page /usr/share/man/man8/rbd-replay-prep.8.gz
complete -c rbd-replay-prep -l window --description 'Requests further apart than \\(aqseconds\\(aq seconds are assumed to be indepen…'
complete -c rbd-replay-prep -l anonymize --description 'Anonymizes image and snap names.'
complete -c rbd-replay-prep -l verbose --description 'Print all processed events to console.'

