# rbd-replay-many
# Autogenerated from man page /usr/share/man/man8/rbd-replay-many.8.gz
complete -c rbd-replay-many -l original-image --description 'Specifies the name (and snap) of the originally traced image.'
complete -c rbd-replay-many -l image-prefix --description 'Prefix of image names to replay against.'
complete -c rbd-replay-many -l exec --description 'Path to the rbd-replay executable.'
complete -c rbd-replay-many -l delay --description 'Delay between starting each client.   Defaults to 0.'

