# rbd-fuse
# Autogenerated from man page /usr/share/man/man8/rbd-fuse.8.gz
complete -c rbd-fuse -s c --description 'Use ceph. conf configuration file instead of the default /etc/ceph/ceph.'
complete -c rbd-fuse -s p --description 'Use pool as the pool to search for rbd images.   Default is rbd.'

