# rbd-replay
# Autogenerated from man page /usr/share/man/man8/rbd-replay.8.gz
complete -c rbd-replay -s c -l conf --description 'Use ceph. conf configuration file instead of the default /etc/ceph/ceph.'
complete -c rbd-replay -s p -l pool --description 'Interact with the given pool.   Defaults to \\(aqrbd\\(aq.'
complete -c rbd-replay -l latency-multiplier --description 'Multiplies inter-request latencies.   Default: 1.'
complete -c rbd-replay -l read-only --description 'Only replay non-destructive requests.'
complete -c rbd-replay -l map-image --description 'Add a rule to map image names in the trace to image names in the replay clust…'
complete -c rbd-replay -l dump-perf-counters --description 'Experimental Dump performance counters to standard out before an image is clo…'

