# rdisc6
# Autogenerated from man page /usr/share/man/man8/rdisc6.8.gz
complete -c rdisc6 -s 1 -l single --description 'Exit as soon as the first advertisement is received.'
complete -c rdisc6 -s h -l help --description 'Display some help and exit.'
complete -c rdisc6 -s m -l multiple --description 'Wait for possible multiple advertisements and print all of them (default).'
complete -c rdisc6 -s n -l numeric --description 'If the optional parameter is not a valid IPv6 address, do not try to resolve …'
complete -c rdisc6 -s q -l quiet --description 'Only display advertised IPv6 prefixes.  Display nothing in case of failure.'
complete -c rdisc6 -s r -l retry --description 'Send ICMPv6 Router Discovery that many times until a reply is received, or ab…'
complete -c rdisc6 -s s -l source --description 'Specify the IPv6 address to be used as the source for the router solicitation…'
complete -c rdisc6 -s V -l version --description 'Display program version and license and exit.'
complete -c rdisc6 -s v -l verbose --description 'Display verbose information.  That is the default.'
complete -c rdisc6 -s w -l wait --description 'Wait  wait_ms  milliseconds for a response before retrying.'

