# rdnssd
# Autogenerated from man page /usr/share/man/man8/rdnssd.8.gz
complete -c rdnssd -s f -l foreground --description 'Do not detach from the console.  Run the program in the foreground.'
complete -c rdnssd -s H -l merge-hook --description 'Execute this hook whenever resolv. conf is updated.'
complete -c rdnssd -s h -l help --description 'Display some help and exit.'
complete -c rdnssd -s p -l pidfile --description 'Override the location of the pidfile.'
complete -c rdnssd -s r -l resolv-file --description 'Set the path to the generated resolv. conf file.'
complete -c rdnssd -s u -l user --description 'Override the user that the program will run as.'
complete -c rdnssd -s V -l version --description 'Display program version and license and exit.'

