# rifftree
# Autogenerated from man page /usr/share/man/man1/rifftree.1.gz
complete -c rifftree -s v --description 'Print version and exit.'
complete -c rifftree -s s --description 'Print the size of each RIFF chunk.'
complete -c rifftree -l flat --description 'First chunk of file is not a list (container) chunk.'
complete -c rifftree -l first-chunk-id --description 'Currently only used in combination with --flat.'
complete -c rifftree -l big-endian --description 'File is in big endian format.  Currently only used in combination with --flat.'
complete -c rifftree -l little-endian --description 'endian type of your machine will be used by default.'

