# rmiregistry-openjdk13
# Autogenerated from man page /usr/share/man/man1/rmiregistry-openjdk13.1.gz
complete -c rmiregistry-openjdk13 -o Joption --description 'Used with any Java option to pass the option following the.'
complete -c rmiregistry-openjdk13 -s J -s J --description 'Java interpreter.'

