# ronn
# Autogenerated from man page /usr/share/man/man1/ronn.1.gz
complete -c ronn -s m -l man --description 'Don\'t generate files, display files as if man(1) were invoked on the roff out…'
complete -c ronn -s S -l server --description 'Don\'t generate files, start an HTTP server at http://localhost:1207/ and serv…'
complete -c ronn -l pipe --description 'Don\'t generate files, write generated output to standard output.'
complete -c ronn -s r -l roff --description 'Generate roff output.'
complete -c ronn -s 5 -l html --description 'Generate output in HTML format.'
complete -c ronn -s f -l fragment --description 'Generate output in HTML format but only the document fragment, not the header…'
complete -c ronn -l manual --description 'The name of the manual this man page belongs to; manual is prominently displa…'
complete -c ronn -l organization --description 'The name of the group, organization, or individual responsible for publishing…'
complete -c ronn -l date --description 'The document\'s published date; date must be formatted YYYY-MM-DD and is displ…'
complete -c ronn -l style --description 'The list of CSS stylesheets to apply to the document.'
complete -c ronn -s w -l warnings --description 'Show troff warnings on standard error when performing roff conversion.'
complete -c ronn -s W --description 'Disable troff warnings.  Warnings are disabled by default.'

