# scribus
# Autogenerated from man page /usr/share/man/man1/scribus.1.gz
complete -c scribus -s l -l lang --description 'Overrides the system locale and runs Scribus in language xx.'
complete -c scribus -o la -l langs-available --description 'Print a list of languages for which user interface translations are available.'
complete -c scribus -s v -l version --description 'Prints the Scribus version number and exits.'
complete -c scribus -s f -l file --description 'Open the specified file.'
complete -c scribus -s h -l help --description 'Print a brief usage summary.'
complete -c scribus -o fi -l font-info --description 'Shows the font file listing as Scribus starts.'
complete -c scribus -o pi -l profile-info --description 'Shows the color profiles listing which Scribus can use.'
complete -c scribus -o pr -l prefs --description 'Use filename as path for user given preferences.'
complete -c scribus -o py -l python-script --description 'Run script in Python [with optional arguments].'
complete -c scribus -o ns -l no-splash --description 'Suppresses display of the splash screen during Scribus start-up.'
complete -c scribus -o nns -l never-splash --description 'Stop the showing of the splashscreen on startup.'
complete -c scribus -o sb -l swap-buttons --description 'Use right to left dialog button ordering (eg.'
complete -c scribus -s u -l upgradecheck --description 'Downloads a file from our scribus server indicating latest available versions.'

