# serialver
# Autogenerated from man page /usr/share/man/man1/serialver.1.gz
complete -c serialver -o classpath --description 'Set search path for application classes and resources. RE  . LP . RS 3.'
complete -c serialver -o show --description 'Displays a simple user interface.'

