# sg_get_elem_status
# Autogenerated from man page /usr/share/man/man8/sg_get_elem_status.8.gz
complete -c sg_get_elem_status -s b -l brief --description 'tbd.'
complete -c sg_get_elem_status -s f -l filter --description 'where FLT is placed in a two bit field called FILTER in the GET PHYSICAL ELEM…'
complete -c sg_get_elem_status -s h -l help --description 'output the usage message then exit.'
complete -c sg_get_elem_status -s H -l hex --description 'output response to this command in ASCII hex.'
complete -c sg_get_elem_status -s i -l inhex --description 'where FN is a function name whose contents are assumed to be ASCII hexadecima…'
complete -c sg_get_elem_status -s m -l maxlen --description 'where LEN is the (maximum) response length in bytes.'
complete -c sg_get_elem_status -s r -l raw --description 'output response in binary (to stdout) unless the --inhex=FN option is also gi…'
complete -c sg_get_elem_status -s R -l readonly --description 'open the DEVICE read-only (e. g.  in Unix with the O_RDONLY flag).'
complete -c sg_get_elem_status -s t -l report-type --description 'where RT will be placed in the REPORT TYPE field of the GET PHYSICAL ELEMENT …'
complete -c sg_get_elem_status -s s -l starting --description 'where ELEM is the placed in the STARTING ELEMENT field of the GET PHYSICAL EL…'
complete -c sg_get_elem_status -s v -l verbose --description 'increase the level of verbosity, (i. e.  debug output).'
complete -c sg_get_elem_status -s V -l version --description 'print the version string and then exit.'

