# shotwell
# Autogenerated from man page /usr/share/man/man1/shotwell.1.gz
complete -c shotwell -s h -l help --description 'Show help options.'
complete -c shotwell -s d -l datadir --description '.'
complete -c shotwell -l no-runtime-monitoring --description '.'
complete -c shotwell -s f -l fullscreen --description '.'
complete -c shotwell -l no-startup-progress --description '.'
complete -c shotwell -s V -l version --description '.'
complete -c shotwell -l display --description '.'

