# simplescreenrecorder
# Autogenerated from man page /usr/share/man/man1/simplescreenrecorder.1.gz
complete -c simplescreenrecorder -l help --description 'Show help message.'
complete -c simplescreenrecorder -l version --description 'Show version and quit.'
complete -c simplescreenrecorder -l logfile --description 'Write log to \\,~/. ssr/log-DATE_TIME. txt\\/ instead of stdout.'
complete -c simplescreenrecorder -l statsfile --description 'Write recording statistics to \\,FILE\\/.'
complete -c simplescreenrecorder -l syncdiagram --description 'Show synchronization diagram (for debugging).'
complete -c simplescreenrecorder -l no-systray --description 'Don\'t show the system tray icon.'
complete -c simplescreenrecorder -l start-hidden --description 'Start the application in hidden form.'

