# smbios-sys-info
# Autogenerated from man page /usr/share/man/man1/smbios-sys-info.1.gz
complete -c smbios-sys-info -l version --description 'show program\'s version number and exit.'
complete -c smbios-sys-info -s h -l help --description 'show this help message and exit.'
complete -c smbios-sys-info -l service-tag --description 'Show or set service tag.'
complete -c smbios-sys-info -l asset-tag --description 'Show or set asset tag.'
complete -c smbios-sys-info -l property-tag --description 'Show or set property tag.'
complete -c smbios-sys-info -l set --description 'Set specified tag to new value.'
complete -c smbios-sys-info -s v -l verbose --description 'Display more verbose output.'
complete -c smbios-sys-info -s q -l quiet --description 'Minimize program output.  Only errors and warnings are displayed.'
complete -c smbios-sys-info -l trace --description 'Enable verbose function tracing.'
complete -c smbios-sys-info -l logconfig --description 'Specify alternate config log.'
complete -c smbios-sys-info -l password --description 'BIOS Setup password for set/activate operations.'
complete -c smbios-sys-info -s r -l rawpassword --description 'Do not auto-convert password to scancodes.'
complete -c smbios-sys-info -l memory-dat --description 'Path to a memory dump file to use instead of real RAM.'
complete -c smbios-sys-info -l cmos-dat --description 'Path to a CMOS dump file to use instead of real CMOS SEE ALSO The full docume…'

