# smbios-wakeup-ctl
# Autogenerated from man page /usr/share/man/man1/smbios-wakeup-ctl.1.gz
complete -c smbios-wakeup-ctl -l version --description 'show program\'s version number and exit.'
complete -c smbios-wakeup-ctl -s h -l help --description 'show this help message and exit.'
complete -c smbios-wakeup-ctl -l hour --description 'Set wakeup hour.  Must be 0-23.'
complete -c smbios-wakeup-ctl -l minute --description 'Set wakeup minute.  Must be 0-59.'
complete -c smbios-wakeup-ctl -l everyday --description 'Set wakeup for every day.'
complete -c smbios-wakeup-ctl -l weekday --description 'Set wakeup for weekdays only.'
complete -c smbios-wakeup-ctl -l disable --description 'Disable wakeups.'
complete -c smbios-wakeup-ctl -s v -l verbose --description 'Display more verbose output.'
complete -c smbios-wakeup-ctl -s q -l quiet --description 'Minimize program output.  Only errors and warnings are displayed.'
complete -c smbios-wakeup-ctl -l trace --description 'Enable verbose function tracing.'
complete -c smbios-wakeup-ctl -l logconfig --description 'Specify alternate config log.'
complete -c smbios-wakeup-ctl -l password --description 'BIOS Setup password for set/activate operations.'
complete -c smbios-wakeup-ctl -s r -l rawpassword --description 'Do not auto-convert password to scancodes.'
complete -c smbios-wakeup-ctl -l memory-dat --description 'Path to a memory dump file to use instead of real RAM.'
complete -c smbios-wakeup-ctl -l cmos-dat --description 'Path to a CMOS dump file to use instead of real CMOS SEE ALSO The full docume…'

