# smbios-battery-ctl
# Autogenerated from man page /usr/share/man/man1/smbios-battery-ctl.1.gz
complete -c smbios-battery-ctl -l version --description 'show program\'s version number and exit.'
complete -c smbios-battery-ctl -s h -l help --description 'show this help message and exit.'
complete -c smbios-battery-ctl -s v -l verbose --description 'Display more verbose output.'
complete -c smbios-battery-ctl -s q -l quiet --description 'Minimize program output.  Only errors and warnings are displayed.'
complete -c smbios-battery-ctl -l trace --description 'Enable verbose function tracing.'
complete -c smbios-battery-ctl -l logconfig --description 'Specify alternate config log.'
complete -c smbios-battery-ctl -l security-key --description 'BIOS pre-calculated security key.'
complete -c smbios-battery-ctl -l password --description 'BIOS Setup password for set/activate operations.'
complete -c smbios-battery-ctl -s r -l rawpassword --description 'Do not auto-convert password to scancodes.'
complete -c smbios-battery-ctl -l memory-dat --description 'Path to a memory dump file to use instead of real RAM.'
complete -c smbios-battery-ctl -l cmos-dat --description 'Path to a CMOS dump file to use instead of real CMOS.'
complete -c smbios-battery-ctl -s c -l battery-charge --description 'This will get the Current Battery Charging State.'
complete -c smbios-battery-ctl -l get-charging-cfg --description 'Get the current Primary Battery Charge Configuration.'
complete -c smbios-battery-ctl -l set-charging-mode --description 'Set the current Primary Battery Charge Configuration.'
complete -c smbios-battery-ctl -l set-custom-charge-interval --description 'Set the percentage bounds for custom charge.  Both must be integers.'

