# smbios-upflag-ctl
# Autogenerated from man page /usr/share/man/man1/smbios-upflag-ctl.1.gz
complete -c smbios-upflag-ctl -l help -s h --description 'Displays this information.'
complete -c smbios-upflag-ctl -l memory_file -s m --description 'Debug: Memory dump file to use instead of physical memory.'
complete -c smbios-upflag-ctl -l cmos_file -s c --description 'Debug: CMOS dump file to use instead of physical cmos.'
complete -c smbios-upflag-ctl -l set -s s --description 'Set Boot To UP Flag to true.'
complete -c smbios-upflag-ctl -l clear --description 'Set Boot To UP Flag to false.'
complete -c smbios-upflag-ctl -l get -s g --description 'Set Boot To UP Flag to true.'
complete -c smbios-upflag-ctl -l version -s v --description 'Display libsmbios version information SEE ALSO The full documentation for smb…'

