# smbios-passwd
# Autogenerated from man page /usr/share/man/man1/smbios-passwd.1.gz
complete -c smbios-passwd -l version --description 'show program\'s version number and exit.'
complete -c smbios-passwd -s h -l help --description 'show this help message and exit.'
complete -c smbios-passwd -l info --description 'Show password information.'
complete -c smbios-passwd -s v -l verbose --description 'Display more verbose output.'
complete -c smbios-passwd -s q -l quiet --description 'Minimize program output.  Only errors and warnings are displayed.'
complete -c smbios-passwd -l trace --description 'Enable verbose function tracing.'
complete -c smbios-passwd -l logconfig --description 'Specify alternate config log.'
complete -c smbios-passwd -l password --description 'BIOS Setup password for set/activate operations.'
complete -c smbios-passwd -s r -l rawpassword --description 'Do not auto-convert password to scancodes.'
complete -c smbios-passwd -l memory-dat --description 'Path to a memory dump file to use instead of real RAM.'
complete -c smbios-passwd -l cmos-dat --description 'Path to a CMOS dump file to use instead of real CMOS SEE ALSO The full docume…'

