# smbios-state-byte-ctl
# Autogenerated from man page /usr/share/man/man1/smbios-state-byte-ctl.1.gz
complete -c smbios-state-byte-ctl -l help -s h --description 'Displays this information.'
complete -c smbios-state-byte-ctl -l memory_file -s m --description 'Debug: Memory dump file to use instead of physical memory.'
complete -c smbios-state-byte-ctl -l cmos_file -s c --description 'Debug: CMOS dump file to use instead of physical cmos.'
complete -c smbios-state-byte-ctl -l set -s s --description 'Set CMOS state byte to new value.'
complete -c smbios-state-byte-ctl -l owner -s o --description 'Set state byte owner.'
complete -c smbios-state-byte-ctl -l version -s v --description 'Display libsmbios version information SEE ALSO The full documentation for smb…'

