# smbios-lcd-brightness
# Autogenerated from man page /usr/share/man/man1/smbios-lcd-brightness.1.gz
complete -c smbios-lcd-brightness -l version --description 'show program\'s version number and exit.'
complete -c smbios-lcd-brightness -s h -l help --description 'show this help message and exit.'
complete -c smbios-lcd-brightness -s v -l verbose --description 'Display more verbose output.'
complete -c smbios-lcd-brightness -s q -l quiet --description 'Minimize program output.  Only errors and warnings are displayed.'
complete -c smbios-lcd-brightness -l trace --description 'Enable verbose function tracing.'
complete -c smbios-lcd-brightness -l logconfig --description 'Specify alternate config log.'
complete -c smbios-lcd-brightness -l security-key --description 'BIOS pre-calculated security key.'
complete -c smbios-lcd-brightness -l password --description 'BIOS Setup password for set/activate operations.'
complete -c smbios-lcd-brightness -s r -l rawpassword --description 'Do not auto-convert password to scancodes.'
complete -c smbios-lcd-brightness -l memory-dat --description 'Path to a memory dump file to use instead of real RAM.'
complete -c smbios-lcd-brightness -l cmos-dat --description 'Path to a CMOS dump file to use instead of real CMOS.'
complete -c smbios-lcd-brightness -l value --description 'Set new value.'
complete -c smbios-lcd-brightness -s b -l battery --description 'Set new value to be used while running on battery power.'
complete -c smbios-lcd-brightness -s a -l ac --description 'Set new value to be used while running on AC power SEE ALSO The full document…'

