# smplayer
# Autogenerated from man page /usr/share/man/man1/smplayer.1.gz
complete -c smplayer -o minigui --description 'Open the mini GUI instead of the default one.'
complete -c smplayer -o mpcgui --description 'Open the mpc GUI instead of the default one.'
complete -c smplayer -o defaultgui --description 'Open the default gui.'
complete -c smplayer -o config-path --description 'Specify the directory for the configuration files (smplayer.'
complete -c smplayer -o send-action --description 'Try to make a connection to another running instance and send to it the speci…'
complete -c smplayer -o actions --description '<action_list> is a list of actions separated by spaces.'
complete -c smplayer -o close-at-end --description 'Close the main window when the file/playlist finishes.'
complete -c smplayer -o no-close-at-end --description 'Do not close the main window when the file/playlist finishes.'
complete -c smplayer -o fullscreen --description 'Play the video in fullscreen mode.'
complete -c smplayer -o no-fullscreen --description 'Play the video in windowed mode.'
complete -c smplayer -o sub --description 'Specify the subtitle file to be loaded (for the first video only).'
complete -c smplayer -o pos --description 'Specify the coordinates where the main window will be displayed.'
complete -c smplayer -o size --description 'Specify the size of the main window.'
complete -c smplayer -s h -o help -l help -s '?' --description 'Show the help message and then exit.'
complete -c smplayer -o add-to-playlist --description 'If there is another instance running, the media will be added to that instanc…'
complete -c smplayer -o disable-server --description 'Disables the server used to communicate with other instances.'

