# sndiod
# Autogenerated from man page /usr/share/man/man8/sndiod.8.gz
complete -c sndiod -s a --description 'Control whether sndiod opens the audio device or the MIDI port only when need…'
complete -c sndiod -s b --description 'The buffer size of the audio device in frames.'
complete -c sndiod -s d --description 'Enable debugging to standard error, and do not disassociate from the controll…'
complete -c sndiod -s e --description 'Attempt to configure the device to use this encoding.  The default is s16.'
complete -c sndiod -s f --description 'Add this sndio 7 audio device to devices used for playing and/or recording.'
complete -c sndiod -s j --description 'Control whether program channels are joined or expanded if the number of chan…'
complete -c sndiod -s L --description 'Specify a local network address sndiod should listen on; sndiod will listen o…'
complete -c sndiod -s m --description 'Set the sub-device mode.'
complete -c sndiod -s q --description 'Expose the given MIDI port.  This allows multiple programs to share the port.'
complete -c sndiod -s r --description 'Attempt to force the device to use this sample rate in Hertz.'
complete -c sndiod -s s --description 'Add name to the list of sub-devices to expose.'
complete -c sndiod -s t --description 'Select the way clients are controlled by MIDI Machine Control (MMC) messages …'
complete -c sndiod -s U --description 'Unit number.'
complete -c sndiod -s v --description 'Software volume attenuation of playback.'
complete -c sndiod -s w --description 'Control sndiod behaviour when the maximum volume of the hardware is reached a…'
complete -c sndiod -s z --description 'The audio device block size in frames.'

