# speedtouch-setup
# Autogenerated from man page /usr/share/man/man1/speedtouch-setup.1.gz
complete -c speedtouch-setup -l pppoe --description 'Setup a PPPoE connection instead of the default PPPoA connection.  SEE ALSO.'

