# src2man
# Autogenerated from man page /usr/share/man/man1/src2man.1.gz
complete -c src2man -s d --description 'Set the date of the man pages.  Defaults to current date.'
complete -c src2man -s n --description 'No man page is created.'
complete -c src2man -s v --description 'Specify the name of the volume to be printed in center header of generated ma…'
complete -c src2man -s r --description 'Specify the project name and release number for the generated manpage.'

