# sshfs
# Autogenerated from man page /usr/share/man/man1/sshfs.1.gz
complete -c sshfs -s o --description 'mount options, see below for details.'
complete -c sshfs -s h -l help --description 'print help and exit.'
complete -c sshfs -s V -l version --description 'print version information and exit.'
complete -c sshfs -s d -l debug --description 'print debugging information.'
complete -c sshfs -s p --description 'equivalent to \\(aq-o port=PORT\\(aq.'
complete -c sshfs -s f --description 'do not daemonize, stay in foreground.'
complete -c sshfs -s s --description 'Single threaded operation.'
complete -c sshfs -s C --description 'equivalent to \\(aq-o compression=yes\\(aq.'
complete -c sshfs -s F --description 'specifies alternative ssh configuration file.'
complete -c sshfs -s 1 --description 'equivalent to \\(aq-o ssh_protocol=1\\(aq.'

