# ssr-glinject
# Autogenerated from man page /usr/share/man/man1/ssr-glinject.1.gz
complete -c ssr-glinject -l help --description 'Show help message.'
complete -c ssr-glinject -l glx-debug --description 'Enables GLX debugging.'
complete -c ssr-glinject -l relax-permissions --description 'Uses mode 666 instead of 600 for shared memory, so that other users can recor…'
complete -c ssr-glinject -l channel --description 'Channel name to use.  The default is \'channel-USERNAME\'.'

