# tcpspray
# Autogenerated from man page /usr/share/man/man1/tcpspray.1.gz
complete -c tcpspray -s 4 -l ipv4 --description 'Force usage of TCP over IPv4.'
complete -c tcpspray -s 6 -l ipv6 --description 'Force usage of TCP over IPv6.'
complete -c tcpspray -s b -l bsize --description 'Send block of the specified byte size (default: 1024).'
complete -c tcpspray -s d -l delay --description 'Waits for the given amount of microseconds after any given was sent before at…'
complete -c tcpspray -s e -l echo --description 'Use the Echo protocol instead of Discard.'
complete -c tcpspray -s f -l fill --description 'Read data from the specified file to fill sent blocks with.'
complete -c tcpspray -s h -l help --description 'Display some help and exit.'
complete -c tcpspray -s n -l count --description 'Send the specified amount of data blocks for the measurements (default: 100).'
complete -c tcpspray -s V -l version --description 'Display program version and license and exit.'
complete -c tcpspray -s v -l verbose --description 'Display more verbose informations.'

