# tint2
# Autogenerated from man page /usr/share/man/man1/tint2.1.gz
complete -c tint2 -l version --description 'Prints version information and exits.'
complete -c tint2 -s c --description 'Specifies which configuration file to use instead of the default.'
complete -c tint2 -s v --description 'Prints version information and exits.'
complete -c tint2 -s h -l help --description 'Display this help and exits.  CONFIGURATION Table of contents.'

