# tracker-miner-rss
# Autogenerated from man page /usr/share/man/man1/tracker-miner-rss.1.gz
complete -c tracker-miner-rss -s '?' -l help --description 'Show summary of options.'
complete -c tracker-miner-rss -s V -l version --description 'Returns the version of this binary.'
complete -c tracker-miner-rss -s v -l verbosity --description 'Sets the logging level, 0=errors, 1=minimal, 2=detailed, 3=debug.'
complete -c tracker-miner-rss -s a -l add-feed --description 'Adds a feed to the Tracker store.  This must be used with   --title option.'
complete -c tracker-miner-rss -l title --description 'option.  An examples of such a URL would be:.'
complete -c tracker-miner-rss -s t --description 'The title to use when adding a feed (see the.'

