# txt2man
# Autogenerated from man page /usr/share/man/man1/txt2man.1.gz
complete -c txt2man -s h --description 'The option -h displays help.'
complete -c txt2man -s d --description 'Set date in header.  Defaults to current date.'
complete -c txt2man -s P --description 'Set pname as project name in header.  Default to uname -s.'
complete -c txt2man -s p --description 'Probe title, section name and volume.'
complete -c txt2man -s t --description 'Set mytitle as title of generated man page.'
complete -c txt2man -s r --description 'Set rel as project name and release.'
complete -c txt2man -s s --description 'Set sect as section in heading, usually a value from 1 to 8.'
complete -c txt2man -s v --description 'Set vol as volume name, i. e.  "Unix user \'s manual".'
complete -c txt2man -s I --description 'Italicize txt in output.  Can be specified more than once.'
complete -c txt2man -s B --description 'Emphasize (bold) txt in output.  Can be specified more than once.'
complete -c txt2man -s T --description 'Text result previewing using PAGER, usually more(1).'
complete -c txt2man -s X --description 'X11 result previewing using gxditview(1).'

