# ubertooth-specan
# Autogenerated from man page /usr/share/man/man1/ubertooth-specan.1.gz
complete -c ubertooth-specan -s l --description 'lower frequency (default 2402) o 2.'
complete -c ubertooth-specan -s u --description 'upper frequency (default 2480) o 2.'
complete -c ubertooth-specan -s g --description 'format output for feedgnuplot o 2.'
complete -c ubertooth-specan -s G --description 'format output for 3D feedgnuplot o 2.'
complete -c ubertooth-specan -o 'd<filename>' --description 'output to file <filename> o 2.'
complete -c ubertooth-specan -s v --description 'print verbose output to stderr o 2.'
complete -c ubertooth-specan -o 'U<0-7>' --description 'set ubertooth device to use ##EXAMPLES To monitor the 2.'

