# ubertooth-scan
# Autogenerated from man page /usr/share/man/man1/ubertooth-scan.1.gz
complete -c ubertooth-scan -s s --description 'hci Scan - use BlueZ to scan for discoverable devices o 2.'
complete -c ubertooth-scan -s x --description 'eXtended scan - retrieve additional information about target devices o 2.'
complete -c ubertooth-scan -s t --description 'scan Time - length of time to sniff packets.  [Default: 20s] o 2.'
complete -c ubertooth-scan -s e --description 'Maximum Access Code Errors (default: 2) o 2.'
complete -c ubertooth-scan -s b --description 'Bluetooth device (default: hci0) o 2.'
complete -c ubertooth-scan -o 'U<0-7>' --description 'which Ubertooth device to use.'

