# ubertooth-ego
# Autogenerated from man page /usr/share/man/man1/ubertooth-ego.1.gz
complete -c ubertooth-ego -s f --description 'Sniff a connection by hopping along channels o 2.'
complete -c ubertooth-ego -s r --description 'Continuously receive packets on a single channel (see -c) o 2.'
complete -c ubertooth-ego -s i --description 'Interfere with a connection Options:.'
complete -c ubertooth-ego -s c --description 'Channel to use for continuous receive (suggested: 2408, 2418, 2423, 2469) o 2.'
complete -c ubertooth-ego -o 'U<0-7>' --description 'Which Ubertooth device to use.'

