# ubertooth-dfu
# Autogenerated from man page /usr/share/man/man1/ubertooth-dfu.1.gz
complete -c ubertooth-dfu -s d --description 'Download - write DFU file to device o 2.'
complete -c ubertooth-dfu -s u --description 'Upload - read DFU file from device o 2.'
complete -c ubertooth-dfu -s r --description 'Reset device after performing operation Miscellaneous:.'
complete -c ubertooth-dfu -s s --description 'Add DFU suffix to binary firmware file o 2.'
complete -c ubertooth-dfu -s U --description 'Which Ubertooth device to use.'

