# ubertooth-rx
# Autogenerated from man page /usr/share/man/man1/ubertooth-rx.1.gz
complete -c ubertooth-rx -s l --description 'Limit UAP recovery, clock recovery, and piconet following to a given LAP.'
complete -c ubertooth-rx -s u --description 'Limit clock recovery and piconet following to a given UAP.'
complete -c ubertooth-rx -s z --description 'Survey mode: recover all LAP and UAP pairs and display them.'
complete -c ubertooth-rx -s i --description 'Input file.  If not specified will perform live capture using Ubertooth.  o 2.'
complete -c ubertooth-rx -s c --description 'Fixed channel for all major modes.'
complete -c ubertooth-rx -s e --description 'Maximum access code bit errors.  [Default: 2] o 2.'
complete -c ubertooth-rx -s t --description 'Timeout in seconds.  If not specified will run indefinitely.'
complete -c ubertooth-rx -s r --description 'Capture packets to PcapNG o 2.'
complete -c ubertooth-rx -s q --description 'Capture packets to PCAP o 2.'
complete -c ubertooth-rx -s d --description 'Capture packets to binary file suitable for use with -i.  Miscellaneous: o 2.'
complete -c ubertooth-rx -s V --description 'Version information o 2.'
complete -c ubertooth-rx -o 'U<0-7>' --description 'Which Ubertooth device to use.'

