# ubertooth-dump
# Autogenerated from man page /usr/share/man/man1/ubertooth-dump.1.gz
complete -c ubertooth-dump -s b --description 'Print ASCII 0 and 1 instead of raw data o 2.'
complete -c ubertooth-dump -s c --description 'Classic Bluetooth modulation (default) o 2.'
complete -c ubertooth-dump -s l --description 'Bluetooth Low Energy (BLE) modulation o 2.'
complete -c ubertooth-dump -s d --description 'Dump to file instead of stdout o 2.'
complete -c ubertooth-dump -s U --description 'which Ubertooth device to use.'

