# ubertooth-afh
# Autogenerated from man page /usr/share/man/man1/ubertooth-afh.1.gz
complete -c ubertooth-afh -s l --description 'LAP of target piconet (3 bytes / 6 hex digits) o 2.'
complete -c ubertooth-afh -s u --description 'UAP of target piconet (1 byte / 2 hex digits) o 2.'
complete -c ubertooth-afh -s m --description 'threshold for channel removal (default: 5) o 2.'
complete -c ubertooth-afh -s r --description 'print AFH channel map once every second (default: print on update) Other opti…'
complete -c ubertooth-afh -s t --description 'timeout for initial AFH map detection (not required) o 2.'
complete -c ubertooth-afh -s e --description 'maximum access code errors (default: 2, range: 0-4) o 2.'
complete -c ubertooth-afh -s V --description 'print version information o 2.'
complete -c ubertooth-afh -s U --description 'set ubertooth device to use.'

