# unpack200-openjdk13
# Autogenerated from man page /usr/share/man/man1/unpack200-openjdk13.1.gz
complete -c unpack200-openjdk13 -o Hvalue -l deflate-hint --description 'Sets the deflation to be true, false, or keep on all entries within a JAR fil…'
complete -c unpack200-openjdk13 -l deflate --description 'the deflation mode on all entries within the output JAR file.'
complete -c unpack200-openjdk13 -s r -l remove-pack-file --description 'Removes the input pack file.'
complete -c unpack200-openjdk13 -s v -l verbose --description 'Displays minimal messages.'
complete -c unpack200-openjdk13 -s q -l quiet --description 'Specifies quiet operation with no messages.'
complete -c unpack200-openjdk13 -s l -l log-file --description 'Specifies a log file where output messages are logged.'
complete -c unpack200-openjdk13 -s '?' -s h -l help --description 'Prints help information about the unpack200 command.'
complete -c unpack200-openjdk13 -s V -l version --description 'Prints version information about the unpack200 command.'
complete -c unpack200-openjdk13 -o Joption --description 'Passes option to the Java Virtual Machine, where option is one of the options…'

