# usbredirserver
# Autogenerated from man page /usr/share/man/man1/usbredirserver.1.gz
complete -c usbredirserver -s p -l port --description 'Set the TCP port to listen on to PORT.'
complete -c usbredirserver -s v -l verbose --description 'Set usbredirserver\'s verbosity level to VERBOSE, this mostly affects USB redi…'

