# viewnior
# Autogenerated from man page /usr/share/man/man1/viewnior.1.gz
complete -c viewnior -l slideshow --description 'Start in slideshow.'
complete -c viewnior -l fullscreen --description 'Start in full screen mode.'
complete -c viewnior -s '?' -l help --description 'Show this help and exit.'
complete -c viewnior -l version --description 'Show version information and exit SEE ALSO.'

