# vinagre
# Autogenerated from man page /usr/share/man/man1/vinagre.1.gz
complete -c vinagre -s '?' -l help --description 'Show help options . SS "Application Options:".'
complete -c vinagre -s F -l file --description 'Opens a . vnc file.'
complete -c vinagre -s f -l fullscreen --description 'Open Vinagre in fullscreen mode.'
complete -c vinagre -l geometry --description 'Specify geometry of the Vinagre window in X11 format.'
complete -c vinagre -s n -l new-window --description 'Create a new toplevel window in an existing instance of Vinagre.'

