# vnstatd
# Autogenerated from man page /usr/share/man/man8/vnstatd.8.gz
complete -c vnstatd -l alwaysadd --description 'Enable automatic creation of new database entries for previously unseen inter…'
complete -c vnstatd -l config --description 'Use  file as configuration file instead of using automatic configuration file…'
complete -c vnstatd -s d -l daemon --description 'Fork process to background and run as a daemon.'
complete -c vnstatd -s D -l debug --description 'Provide additional output for debug purposes.'
complete -c vnstatd -s g -l group --description 'Set daemon process group to  group during startup.'
complete -c vnstatd -l noadd --description 'Disable automatic creation of new database entries for all available interfac…'
complete -c vnstatd -s n -l nodaemon --description 'Stay in foreground attached to the current terminal and start the update proc…'
complete -c vnstatd -s p -l pidfile --description 'Write the process id to  file and use it for locking so that another instance…'
complete -c vnstatd -s s -l sync --description 'Synchronize internal counters in the database with interface counters for all…'
complete -c vnstatd -s u -l user --description 'Set daemon process user to  user during startup.'
complete -c vnstatd -s v -l version --description 'Show current version of the daemon executable.'
complete -c vnstatd -s '?' -l help --description 'Show a command option summary.'

