# vshadowinfo
# Autogenerated from man page /usr/share/man/man1/vshadowinfo.1.gz
complete -c vshadowinfo -s a --description 'shows allocation information.'
complete -c vshadowinfo -s h --description 'shows this help.'
complete -c vshadowinfo -s o --description 'specify the volume offset in bytes.'
complete -c vshadowinfo -s v --description 'verbose output to stderr.'
complete -c vshadowinfo -s V --description 'print version El ENVIRONMENT None FILES None EXAMPLES -literal # vshadowinfo …'

