# vshadowmount
# Autogenerated from man page /usr/share/man/man1/vshadowmount.1.gz
complete -c vshadowmount -s h --description 'shows this help.'
complete -c vshadowmount -s o --description 'specify the volume offset in bytes.'
complete -c vshadowmount -s v --description 'verbose output to stderr.'
complete -c vshadowmount -s V --description 'print version.'
complete -c vshadowmount -s X --description 'extended options to pass to sub system El ENVIRONMENT None FILES None EXAMPLE…'

