# wvWare
# Autogenerated from man page /usr/lib/jvm/default/man/man1/wvWare.1.gz
complete -c wvWare -s c -l charset --description 'word 97 documents are stored in one of two formats, either in 8 bit windows c…'
complete -c wvWare -s p -l password --description 'Due to heroic work done by a great team of workers, the wv library can decryp…'
complete -c wvWare -s d -l dir --description 'If dir is used then any created graphics will be placed in this directory.'
complete -c wvWare -s x -l config --description 'Use this to give the location of the config file.'

