# xpstopng
# Autogenerated from man page /usr/share/man/man1/xpstopng.1.gz
complete -c xpstopng -s '?' -l help --description 'Show help options.'
complete -c xpstopng -s d -l document --description 'The document inside the XPS file to convert.'
complete -c xpstopng -s f -l first --description 'The first page to convert.'
complete -c xpstopng -s l -l last --description 'The last page to convert.'
complete -c xpstopng -s o -l odd --description 'Convert only odd pages.'
complete -c xpstopng -s e -l even --description 'Convert only even pages.'
complete -c xpstopng -s r -l resolution --description 'Horizontal and vertical resolution in PPI (Pixels Per Inch).'
complete -c xpstopng -l rx --description 'Horizontal resolution in PPI (Pixels Per Inch).  The default is 150 PPI.'
complete -c xpstopng -l ry --description 'Vertical resolution in PPI (Pixels Per Inch).  The default is 150 PPI.'
complete -c xpstopng -s x -l crop-x --description 'The x-coordinate of the crop area top left corner.'
complete -c xpstopng -s y -l crop-y --description 'The y-coordinate of the crop area top left corner.'
complete -c xpstopng -s w -l crop-width --description 'The width of crop area.'
complete -c xpstopng -s h -l crop-height --description 'The height of crop area.'
complete -c xpstopng -s t -l transparent-bg --description 'Use a transparent background for pages instead of white.'

