# xpstojpeg
# Autogenerated from man page /usr/share/man/man1/xpstojpeg.1.gz
complete -c xpstojpeg -s '?' -l help --description 'Show help options.'
complete -c xpstojpeg -s d -l document --description 'The document inside the XPS file to convert.'
complete -c xpstojpeg -s f -l first --description 'The first page to convert.'
complete -c xpstojpeg -s l -l last --description 'The last page to convert.'
complete -c xpstojpeg -s o -l odd --description 'Convert only odd pages.'
complete -c xpstojpeg -s e -l even --description 'Convert only even pages.'
complete -c xpstojpeg -s r -l resolution --description 'Horizontal and vertical resolution in PPI (Pixels Per Inch).'
complete -c xpstojpeg -l rx --description 'Horizontal resolution in PPI (Pixels Per Inch).  The default is 150 PPI.'
complete -c xpstojpeg -l ry --description 'Vertical resolution in PPI (Pixels Per Inch).  The default is 150 PPI.'
complete -c xpstojpeg -s x -l crop-x --description 'The x-coordinate of the crop area top left corner.'
complete -c xpstojpeg -s y -l crop-y --description 'The y-coordinate of the crop area top left corner.'
complete -c xpstojpeg -s w -l crop-width --description 'The width of crop area.'
complete -c xpstojpeg -s h -l crop-height --description 'The height of crop area.'

