[General]
firstTime=false

[AppSettings]
firstTime.nomacs.3=false

[GlobalSettings]
recentFiles=/home/lstrohm/.xmonad/xpm/logo-50.xpm, /home/lstrohm/xscreensaver-arch-logo-nogdm/logo-50.xpm
recentFolders=/home/lstrohm/.xmonad/xpm, /home/lstrohm/xscreensaver-arch-logo-nogdm
